use crate::model::{Language, LessonKind};
use ratatui::style::Color;

pub(super) fn lesson_color(kind: LessonKind) -> Color {
    match kind {
        LessonKind::Foundation => Color::LightGreen,
        LessonKind::Warmup => Color::Cyan,
        LessonKind::Chunks => Color::LightGreen,
        LessonKind::CommonWords => Color::Green,
        LessonKind::Words => Color::Green,
        LessonKind::Symbols => Color::Yellow,
        LessonKind::Naming => Color::Magenta,
        LessonKind::CodeBlock => Color::LightBlue,
    }
}

pub(super) fn lesson_title(kind: LessonKind, language: Language) -> &'static str {
    match language {
        Language::Zh => match kind {
            LessonKind::Foundation => "基础输入：综合键位",
            LessonKind::Warmup => "热身：基础键位",
            LessonKind::Chunks => "词块：英文拼写块",
            LessonKind::CommonWords => "日常英语：常用词句",
            LessonKind::Words => "编程基础：技术词汇",
            LessonKind::Symbols => "编程基础：符号和命名",
            LessonKind::Naming => "命名：大小写和前端 API",
            LessonKind::CodeBlock => "代码实战：完整代码块",
        },
        Language::En => match kind {
            LessonKind::Foundation => "Foundation input: mixed keys",
            LessonKind::Warmup => "Warmup: base keys",
            LessonKind::Chunks => "Chunks: English spelling blocks",
            LessonKind::CommonWords => "Everyday English: words and sentences",
            LessonKind::Words => "Programming basics: technical words",
            LessonKind::Symbols => "Programming basics: symbols and naming",
            LessonKind::Naming => "Naming: case and frontend APIs",
            LessonKind::CodeBlock => "Code practice: complete code",
        },
    }
}

pub(super) fn lesson_purpose(kind: LessonKind, language: Language) -> &'static str {
    match language {
        Language::Zh => match kind {
            LessonKind::Foundation => "练键盘行位、横向、竖向和手指过渡",
            LessonKind::Warmup => "把手指放稳，只追正确率",
            LessonKind::Chunks => "练常见开头、结尾和字母组合",
            LessonKind::CommonWords => "练真正高频英文单词，不混大小写",
            LessonKind::Words => "练常见英文单词和变量名",
            LessonKind::Symbols => "解决代码输入掉速的主要来源",
            LessonKind::Naming => "适应 camelCase、PascalCase 和 DOM/React 名称",
            LessonKind::CodeBlock => "练完整代码块和多行结构",
        },
        Language::En => match kind {
            LessonKind::Foundation => "Keyboard rows, columns, and finger transitions",
            LessonKind::Warmup => "Settle fingers; type accurately",
            LessonKind::Chunks => "Prefixes, suffixes, and letter patterns",
            LessonKind::CommonWords => "Common lowercase English words",
            LessonKind::Words => "Frontend words and identifiers",
            LessonKind::Symbols => "Numbers and code symbols",
            LessonKind::Naming => "camelCase, PascalCase, DOM/React",
            LessonKind::CodeBlock => "Complete code blocks and multi-line structure",
        },
    }
}

pub(super) fn text(language: Language, key: &str) -> &'static str {
    match language {
        Language::Zh => match key {
            "terminal_small" => "终端窗口太小，无法显示 KeyLoop。",
            "practice_menu" => "练习菜单",
            "menu_comprehensive" => "综合练习",
            "menu_comprehensive_hint" => "按今日动态计划练完所有组",
            "menu_foundation" => "基础练习",
            "menu_foundation_hint" => "Home/top/bottom row、过渡和基础词专项",
            "menu_everyday" => "日常练习",
            "menu_everyday_hint" => "常见词、日常句子和日常综合",
            "menu_programming" => "编程基础",
            "menu_programming_hint" => "数字符号、操作符、命名和技术词专项",
            "menu_code_specialist" => "编程实战",
            "menu_code_specialist_hint" => "使用全局语言/框架范围练完整代码块",
            "menu_settings" => "全局设置",
            "menu_settings_hint" => "设置界面语言和代码语言/框架范围",
            "menu_stats" => "数据统计",
            "menu_stats_hint" => "查看总览、热力图、弱项和每天练习明细",
            "menu_help" => "↑/↓ 或 J/K：选择 | Enter：开始/进入 | Esc/Q：退出",
            "menu_mode_label" => "今日计划",
            "status_title" => "状态",
            "stats_title" => "数据统计",
            "stats_overview" => "总览",
            "stats_tabs" => "统计页面",
            "stats_dashboard" => "总览诊断",
            "stats_details" => "每日明细",
            "stats_diagnosis" => "弱项诊断",
            "stats_by_day" => "按日期",
            "stats_help" => "←/→ 日期 | Home/End 最新/最早 | Esc 返回 | Q 退出",
            "stats_empty" => "还没有练习记录。完成一次练习后这里会显示统计数据。",
            "stats_empty_day" => "这一天没有练习记录。",
            "stats_no_recent" => "暂无最近记录",
            "stats_none" => "暂无",
            "stats_radar" => "弱项雷达",
            "stats_error_words" => "高错词 / 词块",
            "stats_error_symbols" => "高错符号",
            "stats_key_heat" => "键位热力图",
            "stats_slow_tokens" => "慢词块",
            "foundation_title" => "基础输入",
            "foundation_selected" => "当前专项",
            "foundation_empty" => "没有可用基础输入练习。",
            "foundation_help" => "↑/↓ 或 J/K：选择专项 | 1-9：快速选择 | Enter：开始 | Esc：返回",
            "everyday_title" => "日常练习",
            "everyday_help" => "↑/↓ 或 J/K：选择 | ←/→：切换设置 | Enter：开始 | Esc：返回",
            "programming_title" => "编程基础",
            "programming_help" => "↑/↓ 或 J/K：选择专项 | Enter：开始 | Esc：返回",
            "code_setup_title" => "代码实战设置",
            "code_setup_selected" => "已选范围（匹配任一条件）",
            "code_setup_all" => "全部代码语料（未筛选）",
            "code_setup_empty" => "没有可用代码语料。",
            "code_setup_help" => {
                "↑/↓/←/→ 或 1-4：切换代码块/函数/文件/随机 | Enter：开始 | Esc：返回"
            }
            "settings_title" => "全局设置",
            "settings_menu_help" => "↑/↓：选择设置项 | Enter：进入 | Esc：返回",
            "language_settings_title" => "界面语言设置",
            "language_settings_help" => "↑/↓ 或 ←/→：选择语言 | Enter/Space：应用 | Esc：返回设置",
            "code_filter_settings_title" => "编程语言设置",
            "code_filter_settings_help" => {
                "↑/↓：选择 | Enter/Space：勾选范围 | F：置顶/取消 | D：删除置顶 | Esc：返回设置"
            }
            "today_plan" => "今日练习",
            "today_summary" => "今日总结",
            "daily_progress" => "今日进度",
            "daily_target" => "今日练习目标",
            "practiced" => "已练",
            "remaining" => "还差",
            "done" => "完成",
            "current" => "当前",
            "pending" => "待开始",
            "analysis_title" => "训练依据",
            "analysis_current" => "当前组",
            "analysis_hint" => "诊断只展示最需要处理的一条原因，避免干扰跟打区域。",
            "analysis_empty" => "暂无当前训练依据。",
            "diagnosis_title" => "训练诊断",
            "diagnosis_empty" => "暂无明显弱项，先保持当前节奏。",
            "controls" => "操作",
            "plan_help" => "Enter：开始今日练习 | L：切换语言 | Esc：返回菜单 | Q：退出",
            "daily_goal_hint" => "建议今天练满 20 分钟，可以零碎时间分几次完成。",
            "session_complete" => "本组完成",
            "next_lesson" => "Enter 进入下一组",
            "next_reason" => "下一组原因",
            "adaptive_reason" => "安排原因",
            "next_foundation_group" => "Enter 再来一组基础输入",
            "next_everyday_group" => "Enter 再来一组日常练习",
            "next_programming_group" => "Enter 再来一组编程基础",
            "next_code_group" => "Enter 再来一组代码",
            "finish_today" => "Enter 查看今日总结",
            "complete_help" => "Enter：继续 | R：重练本组 | L：切换语言 | Esc：返回菜单 | Q：退出",
            "summary_help" => "Enter/Esc：回到练习菜单 | L：切换语言 | Q：退出",
            "result_title" => "结果",
            "raw_wpm" => "原始",
            "accuracy" => "正确率",
            "errors" => "错误",
            "backspace" => "退格",
            "slow_focus" => "慢项",
            "slow_focus_empty" => "暂无明显慢项",
            "not_started" => "未开始",
            "source_label" => "来源",
            "esc_help" => "返回/退出",
            "language_help" => "语言",
            "ime_help" => "中文输入法提交会被忽略",
            "ignored_non_ascii" => "已忽略非 ASCII 输入",
            "ghost_title" => "跟打文本",
            "metrics_title" => "指标",
            "progress_title" => "本组进度",
            "current_lesson" => "当前课程",
            "lesson_progress" => "进度",
            "lesson" => "课程",
            "no_completed_lessons" => "今天还没有完成的课程。",
            _ => "",
        },
        Language::En => match key {
            "terminal_small" => "Terminal is too small for KeyLoop.",
            "practice_menu" => "Practice menu",
            "menu_comprehensive" => "Full practice",
            "menu_comprehensive_hint" => "Follow today's adaptive plan",
            "menu_foundation" => "Foundation practice",
            "menu_foundation_hint" => "Home/top/bottom rows, transitions, and basic words",
            "menu_everyday" => "Everyday practice",
            "menu_everyday_hint" => "Common words, daily sentences, and mixed everyday practice",
            "menu_programming" => "Programming basics",
            "menu_programming_hint" => "Numbers, symbols, operators, naming, and technical terms",
            "menu_code_specialist" => "Code practice",
            "menu_code_specialist_hint" => {
                "Use the global language/framework scope for complete code"
            }
            "menu_settings" => "Settings",
            "menu_settings_hint" => "Language and code language/framework scope",
            "menu_stats" => "Stats",
            "menu_stats_hint" => "Overview, heatmap, weak spots, and daily details",
            "menu_help" => "Up/Down or J/K: choose | Enter: start/open | Esc/Q: quit",
            "menu_mode_label" => "plan",
            "status_title" => "Status",
            "stats_title" => "Stats",
            "stats_overview" => "Overview",
            "stats_tabs" => "Stats pages",
            "stats_dashboard" => "Overview diagnosis",
            "stats_details" => "Daily detail",
            "stats_diagnosis" => "Diagnosis",
            "stats_by_day" => "By date",
            "stats_help" => "Left/Right date | Home/End newest/oldest | Esc menu | Q quit",
            "stats_empty" => "No practice records yet. Complete a session to see statistics.",
            "stats_empty_day" => "No practice records on this day.",
            "stats_no_recent" => "no recent records",
            "stats_none" => "none yet",
            "stats_radar" => "Weakness radar",
            "stats_error_words" => "High-error words/chunks",
            "stats_error_symbols" => "High-error symbols",
            "stats_key_heat" => "Key heatmap",
            "stats_slow_tokens" => "Slow tokens",
            "foundation_title" => "Foundation input",
            "foundation_selected" => "Current drill",
            "foundation_empty" => "No foundation input drills are available.",
            "foundation_help" => "Up/Down or J/K: choose | 1-9: jump | Enter: start | Esc: back",
            "everyday_title" => "Everyday practice",
            "everyday_help" => {
                "Up/Down or J/K: choose | Left/Right: setting | Enter: start | Esc: back"
            }
            "programming_title" => "Programming basics",
            "programming_help" => "Up/Down or J/K: choose | Enter: start | Esc: back",
            "code_setup_title" => "Code practice setup",
            "code_setup_selected" => "Selected scope (match any)",
            "code_setup_all" => "all code corpus (no filter)",
            "code_setup_empty" => "No code corpus is available.",
            "code_setup_help" => "Up/Down/Left/Right or 1-4: level | Enter: start | Esc: back",
            "settings_title" => "Settings",
            "settings_menu_help" => "Up/Down: choose setting | Enter: open | Esc: back",
            "language_settings_title" => "Interface language",
            "language_settings_help" => {
                "Up/Down or Left/Right: choose | Enter/Space: apply | Esc: settings"
            }
            "code_filter_settings_title" => "Programming language scope",
            "code_filter_settings_help" => {
                "Up/Down: choose | Enter/Space: toggle scope | F: pin/unpin | D: delete pin | Esc: settings"
            }
            "today_plan" => "Today's practice",
            "today_summary" => "Today summary",
            "daily_progress" => "Daily progress",
            "daily_target" => "Daily target",
            "practiced" => "done",
            "remaining" => "remaining",
            "done" => "done",
            "current" => "current",
            "pending" => "not started",
            "analysis_title" => "Training rationale",
            "analysis_current" => "Current lesson",
            "analysis_hint" => {
                "Diagnosis shows the single most useful reason so the typing area stays focused."
            }
            "analysis_empty" => "No training rationale yet.",
            "diagnosis_title" => "Training diagnosis",
            "diagnosis_empty" => "No clear weak spot yet; keep the current pace.",
            "controls" => "Controls",
            "plan_help" => "Enter: start today's practice | L: language | Esc: menu | Q: quit",
            "daily_goal_hint" => "Recommended target is 20 minutes today. Short sessions count.",
            "session_complete" => "Lesson complete",
            "next_lesson" => "Enter for next lesson",
            "next_reason" => "Next reason",
            "adaptive_reason" => "Reason",
            "next_foundation_group" => "Enter for another foundation group",
            "next_everyday_group" => "Enter for another everyday group",
            "next_programming_group" => "Enter for another programming basics group",
            "next_code_group" => "Enter for another code group",
            "finish_today" => "Enter for today summary",
            "complete_help" => {
                "Enter: continue | R: repeat lesson | L: language | Esc: menu | Q: quit"
            }
            "summary_help" => "Enter/Esc: back to practice menu | L: language | Q: quit",
            "result_title" => "Result",
            "raw_wpm" => "raw",
            "accuracy" => "accuracy",
            "errors" => "errors",
            "backspace" => "backspace",
            "slow_focus" => "Slow focus",
            "slow_focus_empty" => "No obvious slow focus yet",
            "not_started" => "not started",
            "source_label" => "source",
            "esc_help" => "back/exit",
            "language_help" => "language",
            "ime_help" => "Chinese IME commits are ignored",
            "ignored_non_ascii" => "ignored non-ASCII",
            "ghost_title" => "Ghost text",
            "metrics_title" => "Metrics",
            "progress_title" => "Lesson progress",
            "current_lesson" => "Current lesson",
            "lesson_progress" => "progress",
            "lesson" => "lesson",
            "no_completed_lessons" => "No completed lessons today.",
            _ => "",
        },
    }
}
