use crate::model::{Language, LessonKind};
use ratatui::style::Color;

pub(super) fn lesson_color(kind: LessonKind) -> Color {
    match kind {
        LessonKind::Foundation => Color::LightGreen,
        LessonKind::Warmup => Color::Cyan,
        LessonKind::Chunks => Color::LightGreen,
        LessonKind::CommonWords => Color::Green,
        LessonKind::Words => Color::Green,
        LessonKind::Symbols => Color::Yellow,
        LessonKind::Naming => Color::Magenta,
        LessonKind::CodeBlock => Color::LightBlue,
    }
}

pub(super) fn lesson_title(kind: LessonKind, language: Language) -> &'static str {
    match language {
        Language::Zh => match kind {
            LessonKind::Foundation => "基础：键位弱项",
            LessonKind::Warmup => "热身：基础键位",
            LessonKind::Chunks => "词块：英文拼写块",
            LessonKind::CommonWords => "高频词：英语常用词",
            LessonKind::Words => "单词：前端高频词",
            LessonKind::Symbols => "专项：数字和符号",
            LessonKind::Naming => "命名：大小写和前端 API",
            LessonKind::CodeBlock => "代码块：多语言完整片段",
        },
        Language::En => match kind {
            LessonKind::Foundation => "Foundation: weak keys",
            LessonKind::Warmup => "Warmup: base keys",
            LessonKind::Chunks => "Chunks: English spelling blocks",
            LessonKind::CommonWords => "High frequency: common English words",
            LessonKind::Words => "Words: frontend vocabulary",
            LessonKind::Symbols => "Drill: numbers and symbols",
            LessonKind::Naming => "Naming: case and frontend APIs",
            LessonKind::CodeBlock => "Code blocks: complete multi-language snippets",
        },
    }
}

pub(super) fn lesson_purpose(kind: LessonKind, language: Language) -> &'static str {
    match language {
        Language::Zh => match kind {
            LessonKind::Foundation => "根据高错键位自动安排专项",
            LessonKind::Warmup => "把手指放稳，只追正确率",
            LessonKind::Chunks => "练常见开头、结尾和字母组合",
            LessonKind::CommonWords => "练真正高频英文单词，不混大小写",
            LessonKind::Words => "练常见英文单词和变量名",
            LessonKind::Symbols => "解决代码输入掉速的主要来源",
            LessonKind::Naming => "适应 camelCase、PascalCase 和 DOM/React 名称",
            LessonKind::CodeBlock => "练完整代码块，不练单行碎片",
        },
        Language::En => match kind {
            LessonKind::Foundation => "Focused drill chosen from key errors",
            LessonKind::Warmup => "Settle fingers; type accurately",
            LessonKind::Chunks => "Prefixes, suffixes, and letter patterns",
            LessonKind::CommonWords => "Common lowercase English words",
            LessonKind::Words => "Frontend words and identifiers",
            LessonKind::Symbols => "Numbers and code symbols",
            LessonKind::Naming => "camelCase, PascalCase, DOM/React",
            LessonKind::CodeBlock => "Complete code blocks, not one-line fragments",
        },
    }
}

pub(super) fn text(language: Language, key: &str) -> &'static str {
    match language {
        Language::Zh => match key {
            "terminal_small" => "终端窗口太小，无法显示 KeyLoop。",
            "practice_menu" => "练习菜单",
            "menu_comprehensive" => "综合练习",
            "menu_comprehensive_hint" => "按今日动态计划练完所有组",
            "menu_foundation" => "基础练习",
            "menu_foundation_hint" => "按键盘行位、横向、竖向和手指移动专项练",
            "menu_code_specialist" => "代码专项",
            "menu_code_specialist_hint" => "选择语言、框架或项目，连续练代码块",
            "menu_stats" => "数据统计",
            "menu_stats_hint" => "查看总览、热力图、弱项和每天练习明细",
            "menu_help" => "↑/↓ 或 J/K：选择 | Enter：开始/进入 | L：切换语言 | Esc/Q：退出",
            "menu_mode_label" => "今日计划",
            "status_title" => "状态",
            "stats_title" => "数据统计",
            "stats_overview" => "总览",
            "stats_tabs" => "统计页面",
            "stats_dashboard" => "总览诊断",
            "stats_details" => "每日明细",
            "stats_diagnosis" => "弱项诊断",
            "stats_by_day" => "按日期",
            "stats_help" => "←/→ 日期 | Home/End 最新/最早 | L 语言 | Esc 返回 | Q 退出",
            "stats_empty" => "还没有练习记录。完成一次练习后这里会显示统计数据。",
            "stats_empty_day" => "这一天没有练习记录。",
            "stats_no_recent" => "暂无最近记录",
            "stats_none" => "暂无",
            "stats_radar" => "弱项雷达",
            "stats_error_words" => "高错词 / 词块",
            "stats_error_symbols" => "高错符号",
            "stats_key_heat" => "键位热力图",
            "stats_slow_tokens" => "慢词块",
            "foundation_title" => "基础练习",
            "foundation_selected" => "当前专项",
            "foundation_empty" => "没有可用基础练习。",
            "foundation_help" => "↑/↓ 或 J/K：选择专项 | 1-9：快速选择 | Enter：开始 | Esc：返回",
            "code_setup_title" => "代码专项设置",
            "code_setup_selected" => "已选范围（匹配任一条件）",
            "code_setup_all" => "全部代码语料（未筛选）",
            "code_setup_empty" => "没有可用代码语料。",
            "code_setup_help" => {
                "↑/↓ 或 J/K：选择 | Space：勾选 | F：置顶/取消 | D：删除置顶 | A：全选 | C：清空 | Enter：开始 | Esc：返回"
            }
            "today_plan" => "今日练习",
            "today_summary" => "今日总结",
            "daily_progress" => "今日进度",
            "daily_target" => "今日练习目标",
            "practiced" => "已练",
            "remaining" => "还差",
            "done" => "已完成",
            "next" => "下一组",
            "pending" => "待练",
            "controls" => "操作",
            "plan_help" => "Enter：开始今日练习 | L：切换语言 | Esc/Q：退出",
            "daily_goal_hint" => "建议今天练满 20 分钟，可以零碎时间分几次完成。",
            "session_complete" => "本组完成",
            "next_lesson" => "Enter 进入下一组",
            "next_reason" => "下一组原因",
            "adaptive_reason" => "安排原因",
            "next_foundation_group" => "Enter 再来一组基础练习",
            "next_code_group" => "Enter 再来一组代码",
            "finish_today" => "Enter 查看今日总结",
            "complete_help" => "Enter：继续 | R：重练本组 | L：切换语言 | Esc/Q：保存退出",
            "summary_help" => "Enter：回到练习菜单 | L：切换语言 | Esc/Q：保存退出",
            "result_title" => "结果",
            "raw_wpm" => "原始",
            "accuracy" => "正确率",
            "errors" => "错误",
            "backspace" => "退格",
            "slow_focus" => "慢项",
            "slow_focus_empty" => "暂无明显慢项",
            "not_started" => "未开始",
            "source_label" => "来源",
            "esc_help" => "返回/退出",
            "language_help" => "语言",
            "ime_help" => "中文输入法提交会被忽略",
            "ignored_non_ascii" => "已忽略非 ASCII 输入",
            "ghost_title" => "跟打文本",
            "metrics_title" => "指标",
            "progress_title" => "本组进度",
            "current_lesson" => "当前课程",
            "lesson_progress" => "进度",
            "lesson" => "课程",
            "no_completed_lessons" => "今天还没有完成的课程。",
            _ => "",
        },
        Language::En => match key {
            "terminal_small" => "Terminal is too small for KeyLoop.",
            "practice_menu" => "Practice menu",
            "menu_comprehensive" => "Full practice",
            "menu_comprehensive_hint" => "Follow today's adaptive plan",
            "menu_foundation" => "Foundation practice",
            "menu_foundation_hint" => "Rows, horizontal/vertical movement, and finger drills",
            "menu_code_specialist" => "Code focus",
            "menu_code_specialist_hint" => {
                "Choose languages, frameworks, or projects for code drills"
            }
            "menu_stats" => "Stats",
            "menu_stats_hint" => "Overview, heatmap, weak spots, and daily details",
            "menu_help" => "Up/Down or J/K: choose | Enter: start/open | L: language | Esc/Q: quit",
            "menu_mode_label" => "plan",
            "status_title" => "Status",
            "stats_title" => "Stats",
            "stats_overview" => "Overview",
            "stats_tabs" => "Stats pages",
            "stats_dashboard" => "Overview diagnosis",
            "stats_details" => "Daily detail",
            "stats_diagnosis" => "Diagnosis",
            "stats_by_day" => "By date",
            "stats_help" => {
                "Left/Right date | Home/End newest/oldest | L language | Esc menu | Q quit"
            }
            "stats_empty" => "No practice records yet. Complete a session to see statistics.",
            "stats_empty_day" => "No practice records on this day.",
            "stats_no_recent" => "no recent records",
            "stats_none" => "none yet",
            "stats_radar" => "Weakness radar",
            "stats_error_words" => "High-error words/chunks",
            "stats_error_symbols" => "High-error symbols",
            "stats_key_heat" => "Key heatmap",
            "stats_slow_tokens" => "Slow tokens",
            "foundation_title" => "Foundation practice",
            "foundation_selected" => "Current drill",
            "foundation_empty" => "No foundation drills are available.",
            "foundation_help" => "Up/Down or J/K: choose | 1-9: jump | Enter: start | Esc: back",
            "code_setup_title" => "Code focus setup",
            "code_setup_selected" => "Selected scope (match any)",
            "code_setup_all" => "all code corpus (no filter)",
            "code_setup_empty" => "No code corpus is available.",
            "code_setup_help" => {
                "Up/Down or J/K: choose | Space: toggle | F: pin/unpin | D: delete pin | A: all | C: clear | Enter: start | Esc: back"
            }
            "today_plan" => "Today's practice",
            "today_summary" => "Today summary",
            "daily_progress" => "Daily progress",
            "daily_target" => "Daily target",
            "practiced" => "done",
            "remaining" => "remaining",
            "done" => "done",
            "next" => "next",
            "pending" => "pending",
            "controls" => "Controls",
            "plan_help" => "Enter: start today's practice | L: language | Esc/Q: quit",
            "daily_goal_hint" => "Recommended target is 20 minutes today. Short sessions count.",
            "session_complete" => "Lesson complete",
            "next_lesson" => "Enter for next lesson",
            "next_reason" => "Next reason",
            "adaptive_reason" => "Reason",
            "next_foundation_group" => "Enter for another foundation group",
            "next_code_group" => "Enter for another code group",
            "finish_today" => "Enter for today summary",
            "complete_help" => {
                "Enter: continue | R: repeat lesson | L: language | Esc/Q: save and exit"
            }
            "summary_help" => "Enter: back to practice menu | L: language | Esc/Q: save and exit",
            "result_title" => "Result",
            "raw_wpm" => "raw",
            "accuracy" => "accuracy",
            "errors" => "errors",
            "backspace" => "backspace",
            "slow_focus" => "Slow focus",
            "slow_focus_empty" => "No obvious slow focus yet",
            "not_started" => "not started",
            "source_label" => "source",
            "esc_help" => "back/exit",
            "language_help" => "language",
            "ime_help" => "Chinese IME commits are ignored",
            "ignored_non_ascii" => "ignored non-ASCII",
            "ghost_title" => "Ghost text",
            "metrics_title" => "Metrics",
            "progress_title" => "Lesson progress",
            "current_lesson" => "Current lesson",
            "lesson_progress" => "progress",
            "lesson" => "lesson",
            "no_completed_lessons" => "No completed lessons today.",
            _ => "",
        },
    }
}
