# Authored everyday English articles: one short/medium/long per level.
# Each: (level, length, title, [(en_paragraph, zh_paragraph), ...])

ARTICLES = [
("high_school", "short", "A Morning at the Market", [
 ("Every Saturday morning, my mother and I walk to the market near the river. We bring two big bags and a small list of things to buy. The air is cool, and the street is full of people, bikes, and the smell of fresh bread.",
  "每个周六早上，我和妈妈步行去河边的市场。我们带上两个大袋子和一张小购物清单。空气凉爽，街上满是行人、自行车和新鲜面包的香味。"),
 ("We always stop at the same fruit stand first. The old man there knows us well, and he often gives me an apple for free. Mother picks the vegetables slowly and asks about the price of fish.",
  "我们总是先在同一个水果摊停下。摊主老爷爷很熟悉我们，常常免费送我一个苹果。妈妈慢慢挑着蔬菜，还问鱼的价格。"),
 ("On the way home, the bags are heavy, but I like to carry them. We talk about what to cook for lunch, and the morning always feels too short.",
  "回家的路上袋子很重，但我喜欢提着它们。我们聊着午饭做什么，总觉得早晨过得太快。"),
]),
("high_school", "medium", "My First Day at a New School", [
 ("Last year my family moved to a new city because of my father's work. I was happy about the bigger house, but I was afraid of one thing: the new school. I did not know anyone there, and I am not good at talking to new people.",
  "去年因为爸爸的工作，我们全家搬到了一个新城市。我对更大的房子很满意，但有一件事让我害怕：新学校。那里我谁都不认识，而且我不擅长和陌生人说话。"),
 ("On the first morning, I stood at the school gate for a long time. Students walked past me in groups, laughing and talking. I felt very small. Then a tall boy stopped and asked if I was new. He said his name was Daniel and that his family had moved here two years ago, so he knew how I felt.",
  "第一天早上，我在校门口站了很久。学生们成群结队地走过，又说又笑。我觉得自己很渺小。这时一个高个子男生停下来，问我是不是新来的。他说他叫丹尼尔，两年前他家也搬来这里，所以他懂我的感受。"),
 ("Daniel showed me where my classroom was and sat with me at lunch. In the afternoon, he introduced me to his friends, and one of them lived on my street. By the end of the day, the school did not feel so strange anymore.",
  "丹尼尔带我找到教室，午饭时还和我坐在一起。下午他把我介绍给他的朋友们，其中一个就住在我家那条街上。一天结束时，学校已经不再那么陌生了。"),
 ("Now, when I see a new student standing alone at the gate, I always walk over and say hello first. I remember how much one small hello can change a whole year.",
  "现在，每当我看到新同学独自站在校门口，我总会主动走过去打招呼。我记得一句小小的问候能改变整整一年。"),
]),
("high_school", "medium", "The Garden Project", [
 ("Our class started a small garden behind the school library last spring. The idea came from our science teacher, Miss Lee. She said that we could learn more from growing real plants than from reading about them in books. At first, many of us thought it would be boring work.",
  "去年春天，我们班在学校图书馆后面开辟了一个小菜园。这个主意来自我们的科学老师李老师。她说，亲手种植物比在书本上读到的学得更多。起初，我们很多人觉得这会是无聊的活儿。"),
 ("We were wrong. There was so much to do and to decide. Which plants need full sun? How often should we water them? Why did the tomatoes grow well on one side but not on the other? Every week brought a new problem, and we had to find the answers together.",
  "我们错了。要做的事和要做的决定太多了。哪些植物需要充足的阳光？多久浇一次水？为什么西红柿在一边长得好，另一边却不行？每周都有新问题，我们必须一起寻找答案。"),
 ("The hardest time came in July. The weather was very hot, and school was closed for the holiday. We made a plan: every student took two days each month to come and water the garden. Nobody wanted to be the one who let the plants die, so everyone kept their promise.",
  "最难的时候是七月。天气非常热，学校又放假了。我们订了一个计划：每个学生每月负责两天来浇水。谁都不想成为让植物枯死的那个人，所以每个人都信守了承诺。"),
 ("In September, we picked our first full harvest: tomatoes, beans, and more green vegetables than our class could eat. We sold some at the school gate and gave the rest to the teachers. With the money, we bought seeds for next year.",
  "九月，我们迎来了第一次大丰收：西红柿、豆角，还有多到全班吃不完的绿叶蔬菜。我们在校门口卖掉了一些，剩下的送给了老师们。用赚来的钱，我们买了来年的种子。"),
 ("Looking back, I think Miss Lee was right, but not only about science. The garden taught us how to share work, how to keep going when things get hard, and how good it feels to build something with your own hands.",
  "回头看，我觉得李老师说得对，但不仅仅是关于科学。菜园教会了我们如何分担工作，如何在困难时坚持下去，以及亲手创造一样东西的感觉有多好。"),
]),
("cet4", "short", "Why I Stopped Buying Coffee Every Day", [
 ("For three years, I bought a cup of coffee on my way to work every single morning. It was a small pleasure, and I never thought about the cost. Then one evening, I did the math on my phone: the habit was costing me more than a holiday trip every year.",
  "整整三年，我每天早上上班路上都会买一杯咖啡。这是个小小的享受，我从没想过它的花销。直到一天晚上，我用手机算了一笔账：这个习惯每年花掉的钱比一次度假旅行还多。"),
 ("I did not give up coffee. Instead, I bought a simple machine and started making it at home. The first week felt strange, but soon I actually began to enjoy the quiet ten minutes in my kitchen before leaving the house.",
  "我没有戒掉咖啡，而是买了一台简单的咖啡机，开始在家自己做。第一周感觉很别扭，但很快我竟开始享受出门前在厨房里安静的十分钟。"),
 ("Now I put the money I save into a small account. It is not about the coffee anymore. It is about noticing the small choices that quietly shape a whole year.",
  "现在我把省下的钱存进一个小账户。这已经不再是咖啡的问题，而是学会留意那些悄悄塑造一整年的小选择。"),
]),
("cet4", "medium", "The Lost Phone", [
 ("Last month, I left my phone in a taxi. I realized it only after the car had driven away, and for a moment I just stood on the street, not knowing what to do. My whole life seemed to be in that phone: photos, messages, bank cards, and the numbers of everyone I know.",
  "上个月，我把手机落在了出租车上。直到车开走我才发现，那一刻我呆站在街头，不知所措。我的整个生活似乎都在那部手机里：照片、信息、银行卡，还有所有认识的人的号码。"),
 ("I borrowed a stranger's phone to call my own number. No one answered the first time, or the second. I was ready to give up when, on the third try, a voice said hello. It was the driver. He had found the phone on the back seat and had already turned around to look for me.",
  "我借了一位路人的手机拨打自己的号码。第一次没人接，第二次也没有。我正准备放弃时，第三次拨打有人应了一声。是那位司机。他在后座发现了手机，并且已经掉头回来找我。"),
 ("Twenty minutes later, he handed it back and refused to take any money. He said that last year someone had returned his daughter's lost bag, and he was simply passing the kindness on. I thanked him again and again, and he just smiled and drove away.",
  "二十分钟后，他把手机还给我，并拒绝收任何酬谢。他说去年有人把他女儿丢失的包送了回来，他只是把这份善意传递下去。我一再道谢，他只是笑笑，开车走了。"),
 ("That evening I added a new contact to my phone: the driver's number, saved under the name A Friend. The city feels different when you know it is full of people like him.",
  "那天晚上，我在手机里存了一个新联系人：那位司机的号码，名字存的是“一位朋友”。当你知道城市里满是这样的人时，它给你的感觉都不一样了。"),
]),
("cet4", "medium", "Learning to Cook Changed My Life", [
 ("When I moved to the city for my first job, I knew how to cook exactly three things: instant noodles, fried eggs, and rice. For the first few months, I ate out for almost every meal. It was easy and fast, but by the end of each month, my wallet was empty and I felt tired all the time.",
  "刚到城市开始第一份工作时，我只会做三样东西：泡面、煎蛋和米饭。头几个月，我几乎顿顿在外面吃。这样又方便又快，但每到月底钱包就空了，而且我总觉得疲惫。"),
 ("The change started with a video my sister sent me. It showed a simple tomato soup, made in fifteen minutes with five things from any supermarket. I tried it on a Sunday evening. The kitchen was a mess afterwards, and the soup was too salty, but I had made it myself, and it was warm and real.",
  "改变始于姐姐发给我的一个视频。视频里是一道简单的番茄汤，用超市随处可买的五样东西，十五分钟就能做好。我在一个周日晚上试了试。事后厨房一片狼藉，汤也太咸了，但那是我亲手做的，温暖而真实。"),
 ("After that, I cooked one new dish every weekend. Some were terrible. I once forgot a chicken in the oven for two hours, and my smoke alarm became famous in the building. But slowly, I built a small list of meals I could make well, and then a bigger one.",
  "从那以后，我每个周末学做一道新菜。有些做得很糟。有一次我把一只鸡忘在烤箱里两个小时，烟雾报警器在整栋楼都出了名。但慢慢地，我攒下了一小份拿手菜清单，后来清单越来越长。"),
 ("Cooking changed more than my dinner. I started inviting friends over instead of meeting them in noisy restaurants. We talked more and spent less. I began to visit the morning market near my street, where shopping is slower but the food is fresher and the sellers remember your face.",
  "做饭改变的不只是我的晚餐。我开始邀请朋友来家里，而不是在嘈杂的餐馆见面。我们聊得更多，花得更少。我开始逛家附近的早市，在那里买东西节奏更慢，但食材更新鲜，摊主还会记住你的脸。"),
 ("Two years later, I still keep the first recipe my sister sent me. The paper is marked with oil and sauce, and the soup is still sometimes too salty. But every time I make it, I remember that big changes often begin with one small, simple step.",
  "两年后的今天，我仍然保留着姐姐发给我的第一份食谱。纸上沾满了油渍和酱汁，汤有时还是会太咸。但每次做这道汤，我都会想起：大的改变往往始于一个小而简单的开始。"),
]),
("cet6", "short", "The Quiet Power of Walking Meetings", [
 ("My manager has an unusual habit: when a discussion needs only two people, she refuses to book a meeting room. Instead, we walk. There is a small park behind our office building, and one slow loop around it takes about twenty minutes, which is exactly the length of a useful conversation.",
  "我的经理有个不寻常的习惯：只需要两个人讨论的事情，她从不订会议室，而是带你去散步。我们办公楼后面有个小公园，慢慢绕一圈大约二十分钟，恰好是一次有效谈话的长度。"),
 ("At first I found it strange to discuss serious work without a screen between us. But walking side by side changes the conversation. Nobody checks messages. Difficult points feel less like an attack when you are both facing the same direction.",
  "起初我觉得不对着屏幕谈正事很奇怪。但并肩行走改变了谈话本身。没有人查看消息。当两个人面朝同一个方向时，尖锐的问题听起来也不那么像指责了。"),
 ("Research supports her habit, apparently, but she never quotes it. She simply says that the best ideas in her career arrived somewhere between the second corner and the third bench.",
  "据说研究也支持她的习惯，但她从不引用。她只是说，她职业生涯中最好的想法，都出现在第二个拐角和第三条长椅之间的某个地方。"),
]),
("cet6", "medium", "When the Lights Went Out", [
 ("The storm hit our neighborhood on a Friday night, and by ten the whole district had lost power. At first, everyone treated it as a small adventure. We lit candles, found the old radio, and the children thought the dark staircase was the best game of the year.",
  "暴风雨在周五晚上袭击了我们的街区，十点钟整个片区都停了电。起初，大家都把这当成一场小小的冒险。我们点起蜡烛，翻出旧收音机，孩子们觉得漆黑的楼梯是今年最好玩的游戏。"),
 ("By the second day, the adventure had worn off. Food in the fridge was going bad, phones were dead, and the elderly couple on the fourth floor could not manage the stairs in the dark. That was when the building chat group, usually full of complaints about parking, quietly changed its character.",
  "到了第二天，新鲜感消失了。冰箱里的食物开始变质，手机没了电，四楼的老两口在黑暗中爬不了楼梯。就在这时，平时满是停车抱怨的楼栋群，悄悄变了样。"),
 ("Someone with a gas stove offered to boil water for the whole floor. A young man collected everyone's power banks and charged them at his office across the city. Two teenagers made a list of elderly neighbors and knocked on their doors twice a day, carrying water and asking what they needed.",
  "有煤气灶的人主动为整层楼烧开水。一个小伙子收齐了大家的充电宝，带到城另一头的办公室去充电。两个中学生列了一份独居老人名单，每天敲两次门，送水并询问他们需要什么。"),
 ("Power returned on the fourth evening, and the building lit up window by window to the sound of cheering. The chat group went back to arguing about parking spaces within a week. But something had changed: now the arguments end sooner, and they always end politely.",
  "第四天傍晚来电了，整栋楼的窗户在欢呼声中一扇接一扇亮起。不到一周，群里又开始为车位争吵。但有些东西变了：如今的争吵结束得更快，而且总是以客气收场。"),
]),
("cet6", "medium", "The Second Life of an Old Factory", [
 ("The textile factory at the edge of our city closed down when I was still in primary school. For fifteen years, the long brick buildings stood empty behind a rusting fence, and the only visitors were stray cats and teenagers looking for somewhere to be alone. Most people assumed the site would eventually be cleared for apartment towers.",
  "我还在上小学时，城边的那家纺织厂就倒闭了。十五年里，长长的砖楼空荡荡地立在锈蚀的围栏后面，唯一的访客是流浪猫和想找地方独处的少年。大多数人以为这块地最终会被推平，盖起公寓楼。"),
 ("The plan that actually arrived was stranger and better. A group of young architects rented the main hall for almost nothing and turned one corner into a workshop. Furniture makers followed, then a bakery that needed cheap space for its ovens, then a climbing gym under the high ceilings where machines once stood.",
  "实际到来的计划更出人意料，也更好。一群年轻建筑师以近乎免费的价格租下主厂房，把一个角落改成了工作室。家具匠人跟着来了，然后是一家需要廉价空间放烤炉的面包店，再后来，曾经摆放机器的高大车间里开起了攀岩馆。"),
 ("The city government, to its credit, resisted the urge to over-plan. It repaired the roofs, installed proper wiring, and then largely stepped back. Rents stayed low on one condition: every business had to open its doors to the public a few days each month, whether for classes, tours, or simple conversation.",
  "值得称道的是，市政府克制住了过度规划的冲动。他们修好屋顶，装好电路，然后基本退到一旁。低租金只有一个条件：每家店每月必须向公众开放几天，无论是办课程、做参观，还是单纯聊天。"),
 ("My grandmother worked in that factory for twenty years, and last spring I finally brought her back. She walked through the bakery that now fills her old workshop, touched the brick wall by the window, and stood quietly for a while. Then she bought two loaves of bread and told the young baker, with great authority, that the light in this corner had always been the best in the building.",
  "我祖母曾在那家工厂工作了二十年，去年春天我终于带她故地重游。她穿过如今开在她旧车间里的面包店，摸了摸窗边的砖墙，安静地站了一会儿。然后她买了两条面包，以十足权威的口吻告诉年轻的面包师：这个角落的光线从来都是整栋楼里最好的。"),
 ("Cities are often praised for what they build and criticized for what they tear down. The old factory taught our city a third option: keep the walls, change the life inside them, and let memory and the future share the same address.",
  "城市常因建造了什么而受赞扬，因拆除了什么而被批评。这座老工厂教会了我们的城市第三种选择：留住墙体，更换墙内的生活，让记忆与未来共用同一个地址。"),
]),
("postgraduate", "short", "The Reading Group Experiment", [
 ("Our department tried a small experiment last term: a reading group where doctoral students from completely different fields discussed one difficult paper each week. A historian, two biologists, an economist, and a computer scientist around one table sounds like the opening of a joke, and for the first month it often felt like one.",
  "上学期我们系做了个小实验：组织一个读书会，让来自完全不同领域的博士生每周讨论一篇难懂的论文。一位历史学家、两位生物学家、一位经济学家和一位计算机科学家围坐一桌，听起来像笑话的开头——头一个月也确实常常像个笑话。"),
 ("The discomfort turned out to be the point. Forced to explain methods without jargon, we discovered how many of our certainties were habits rather than arguments. The economist's questions about my data were naive in form and devastating in substance.",
  "但这种不适恰恰是关键。被迫用大白话解释研究方法时，我们发现自己的许多确信只是习惯，而非论证。经济学家对我数据的提问，形式上天真，实质上致命。"),
 ("Attendance was voluntary, and yet nobody quit. Whatever we lost in comfort, we gained in sharper questions, and sharper questions, we slowly realized, are the true currency of research.",
  "读书会自愿参加，却没有一个人退出。我们失去的是舒适，换来的是更锐利的问题——而我们慢慢明白，更锐利的问题才是研究的真正通货。"),
]),
("postgraduate", "medium", "On Keeping a Failure Log", [
 ("Midway through my second year, my supervisor gave me the strangest advice I had received in graduate school: start writing down your failures, she said, with the same care you give your results. Not as confession, but as data. I thought the idea was slightly absurd and started the log mainly to please her.",
  "研二过半时，导师给了我读研以来最奇怪的建议：开始记录你的失败，她说，要像对待成果一样认真。不是当作忏悔，而是当作数据。我觉得这主意有点荒唐，记日志最初主要是为了让她满意。"),
 ("The early entries were painful to write. A promising method that collapsed after three weeks of work. A beautiful hypothesis killed by an ugly control experiment. An interview study that taught me mostly about my own poor questions. Reading them back, I expected to feel discouraged.",
  "最初的几条写起来很痛苦。一个看起来大有希望的方法，三周的工作后宣告失败。一个漂亮的假设，被一个难看的对照实验干掉。一项访谈研究，主要教会了我自己的提问有多差。重读这些记录时，我以为自己会泄气。"),
 ("Instead, patterns appeared. My failures were not random; they clustered. I trusted clean simulations too early and real participants too late. I designed experiments to confirm ideas rather than to break them. The log did not make me fail less, at first, but it made me fail differently, which turned out to matter more.",
  "结果却浮现出规律。我的失败不是随机的，而是成簇出现的。我过早相信干净的模拟，过晚才接触真实的参与者。我设计实验是为了证实想法，而不是推翻想法。这本日志起初并没有让我少失败，但让我以不同的方式失败——事实证明这更重要。"),
 ("I still keep the log, now in its fourth notebook. The results sections of my papers are built, page by page, on everything those notebooks contain and the papers never mention.",
  "这本日志我至今还在记，已经是第四个本子了。我论文里的结果部分，正是一页一页建立在这些本子所记录、而论文从不提及的一切之上。"),
]),
("postgraduate", "long", "What the Archive Did Not Say", [
 ("I went into the city archive looking for a clean story. My thesis, in its early outline, argued that the great school reform of the 1950s had been designed in the capital and simply rolled out across the provinces. The official documents, neatly bound and stamped, seemed to agree with me. Plans were issued; circulars followed; reports of successful implementation flowed back. On paper, the machine turned smoothly.",
  "我走进市档案馆时，想找的是一个干净利落的故事。我的论文初稿主张：上世纪五十年代的大教育改革由首都设计，然后简单地推行到各省。那些装订整齐、盖着公章的官方文件似乎也同意我的观点。计划下发，通知跟进，成功执行的报告源源不断地回流。在纸面上，这部机器运转顺畅。"),
 ("The trouble began in a box of unsorted correspondence that the archivist almost did not show me. Letters from school principals, written in careful and formal language, kept asking the same strange question in different ways: how were they to apply rules written for large city schools in villages where one teacher taught four grades in a single room? The capital's replies were polite and almost entirely empty.",
  "麻烦始于一箱未经整理的来往信件——档案管理员差点没拿给我看。校长们的来信措辞谨慎而正式，却用不同的方式反复追问同一个奇怪的问题：为大城市学校制定的规则，要如何应用到一位教师在一间教室里同时教四个年级的乡村学校？而首都的回复客气，却几乎全是空话。"),
 ("Reading further, I found the real mechanism. Provincial inspectors, caught between impossible instructions and real classrooms, had quietly developed their own translations of the reform. They reported compliance upward in the language the capital expected, while teaching principals, in person and off the record, which parts of the rules could be bent and which must be obeyed. The reform that reached the children was written neither in the capital nor in the provinces, but in that unrecorded space between them.",
  "继续读下去，我找到了真正的机制。夹在不可能完成的指令与真实课堂之间的省级督学，悄悄发展出了他们自己对改革的“翻译”。他们用首都期待的语言向上汇报合规情况，同时当面、不留记录地告诉校长们：规则的哪些部分可以变通，哪些必须遵守。最终抵达孩子们的那场改革，既不是在首都写就的，也不是在各省写就的，而是诞生于两者之间那个没有记录的空间。"),
 ("My thesis survived, but only after its central claim had been turned inside out. The reform succeeded, where it did, not because the plan was strong but because the system quietly allowed it to be weak in the right places. The stamped documents told the story the state wished to remember; the unsorted box held the story as it happened.",
  "我的论文活了下来，但其核心论点被彻底翻转。改革在成功的地方之所以成功，不是因为计划强大，而是因为这个体系悄悄允许它在恰当的地方保持弱势。盖章的文件讲述的是国家希望被记住的故事；那箱未经整理的信件里，装着事情真实发生的样子。"),
 ("The discovery changed my method as much as my argument. I stopped reading reports as records of events and began reading them as performances, asking in each case who the intended audience was and what the writer needed that audience to believe. A document, I learned, is an action before it is a source, and the question of what it does must come before the question of what it says.",
  "这个发现改变我的方法，正如它改变我的论点。我不再把报告当作事件的记录来读，而是当作表演来读，每一次都追问：预期的读者是谁，写作者需要这位读者相信什么。我学到：一份文件在成为史料之前，首先是一个动作；先问它做了什么，才能问它说了什么。"),
 ("I now tell new students in our group two things before their first archive visit. First, read everything that was filed, because that is the skeleton of your story. Second, ask the archivist what nobody has requested in years, because somewhere in the unrequested boxes lives the part of the past that did not fit the forms.",
  "如今，每当组里有新生第一次去档案馆，我都会叮嘱两件事。第一，把归档的东西全部读完，因为那是你故事的骨架。第二，问问档案管理员有什么是多年来无人调阅的——因为在那些无人问津的箱子里，住着那段装不进表格的过去。"),
]),
("toefl_ielts", "short", "The Honest Map", [
 ("Every transit map lies a little. Lines that twist through old neighborhoods are drawn straight; stations separated by a difficult hill appear side by side. Designers defend these lies as kindness: a map that showed every curve would be accurate, unreadable, and useless to the passenger trying to catch a train.",
  "每一张交通图都会撒一点谎。穿过老城区的曲折线路被画成直线；隔着一座难爬的山丘的两个车站，看起来近在咫尺。设计师为这些谎言辩护，称之为善意：一张画出每个弯道的图固然准确，却没法阅读，对赶车的乘客毫无用处。"),
 ("The interesting question is where kindness ends. A famous redesign once made the river vanish entirely, and tourists, trusting the map over the ground, walked confidently into dead ends for years.",
  "有趣的问题在于善意的边界在哪里。一次著名的改版曾让整条河从图上彻底消失，而相信地图胜过相信脚下的游客们，多年来自信地走进一条条死路。"),
 ("Good maps, like good explanations, simplify the truth without betraying it. The test is simple: does the lie help the reader arrive, or only help the drawing look clean?",
  "好地图和好的解释一样，简化真相而不背叛真相。检验标准很简单：这个谎言是帮读者抵达目的地，还是只是让图面显得干净？"),
]),
("toefl_ielts", "medium", "The Slow Death of the Phone Call", [
 ("My grandmother treats an unanswered phone call as a minor emergency; my younger colleagues treat an unannounced one as a minor offense. Between these two reactions lies a quiet revolution in manners. In barely two decades, the voice call has moved from the default form of distant communication to something close to an intrusion, reserved for emergencies, deliveries, and the very old.",
  "我祖母把没人接的电话当作小型紧急事件；我的年轻同事则把未经预约的来电当作一种轻微的冒犯。在这两种反应之间，藏着一场礼仪的静悄悄的革命。短短二十年间，语音通话从远距离交流的默认方式，变成了近乎打扰的东西——只留给急事、快递和年纪很大的人。"),
 ("The usual explanation blames convenience: text can wait, voice cannot. But convenience alone misses the deeper shift. A call demands that two attentions meet at the same moment; a message politely declines that demand. We have collectively decided that another person's time is not ours to claim without warning, and the decision has costs as well as courtesies.",
  "通常的解释归因于便利：文字可以等，语音不能。但仅凭便利无法说明更深层的变化。一通电话要求两个人的注意力在同一时刻相遇；而一条消息礼貌地拒绝了这种要求。我们集体决定：他人的时间不容我们不打招呼就占用。这个决定带来了礼貌，也带来了代价。"),
 ("Something is lost when every conversation is scheduled. The accidental call that ran long, the voice that betrayed worry beneath cheerful words, the argument resolved in ten minutes because neither side could hide behind careful editing: these were not interruptions of relationships but part of their fabric.",
  "当每一次交谈都需要预约时，有些东西就丢失了。那通意外聊了很久的电话，那个在欢快言辞下泄露出担忧的声音，那场十分钟就化解的争执——因为谁也无法躲在字斟句酌的编辑背后。这些从来不是关系的打扰，而是关系的织体本身。"),
 ("I do not expect the trend to reverse, and mostly I do not want it to. But once a month I call an old friend without warning, and we both pretend, for an hour, that it is still an ordinary thing to do.",
  "我不指望这个趋势逆转，大体上也不希望它逆转。但每个月我都会不打招呼地给一位老友打个电话，然后我们俩在一个小时里假装：这仍是一件再平常不过的事。"),
]),
("toefl_ielts", "long", "In Defense of Difficult Books", [
 ("There is a moment, familiar to every serious reader, when a book stops cooperating. The sentences grow long and strange; the argument disappears around a corner; the characters refuse to explain themselves. The modern instinct, trained by interfaces that apologize for every second of friction, is to conclude that the book has failed and to reach for something smoother. I want to argue the opposite: that this moment of resistance is precisely where the value of reading begins.",
  "每个认真的读者都熟悉这样一个时刻：一本书突然不再配合。句子变得冗长而陌生；论证在某个拐角消失不见；人物拒绝解释自己。被那些为每一秒钟阻力道歉的界面训练出来的现代直觉会断定：这本书失败了，然后伸手去拿更顺滑的东西。我想论证的恰恰相反：这个产生抗拒的时刻，正是阅读价值的起点。"),
 ("Ease is a wonderful property in tools and a suspicious one in ideas. A difficult book forces a confession that easy media never demand: the admission that your current mental furniture cannot seat this thought. Confusion, in this light, is not a failure state but a diagnostic one. It marks, with great precision, the exact edge of what you currently understand, which is information no comfortable book can provide.",
  "省力是工具的美德，却是思想的可疑品质。一本难读的书会迫使你做出轻松媒介从不要求的坦白：承认你现有的思维家具安放不下这个想法。这样看来，困惑不是失败状态，而是诊断状态。它以极高的精度标出了你当前理解力的确切边界——这是任何一本舒适的书都无法提供的信息。"),
 ("The skill that difficult books train is not intelligence but a kind of tolerance: the ability to keep walking while lost. Researchers call this staying in the problem; readers know it as the strange discipline of continuing past the point where understanding fails, trusting that the fog is part of the landscape and not a sign that the road has ended. Every demanding field, from mathematics to medicine, ultimately rests on this tolerance, and almost nothing in contemporary life exercises it.",
  "难读的书训练的不是智力，而是一种耐受力：迷路时继续行走的能力。研究者称之为“待在问题里”；读者则知道这是一种奇特的纪律——在理解失效之处继续前行，并相信迷雾是风景的一部分，而非道路终结的标志。从数学到医学，每一个高要求的领域最终都建立在这种耐受力之上，而当代生活中几乎没有什么东西在锻炼它。"),
 ("None of this is a defense of obscurity for its own sake. Some books are difficult because they protect weak ideas with strong vocabulary, and learning to tell honest difficulty from decorative difficulty is itself part of the discipline. The honest kind repays every hour: the argument that finally assembles itself, three chapters late, arrives with a force that no summary could carry, precisely because you built the road it traveled on.",
  "这一切并不是在为故弄玄虚辩护。有些书之所以难读，是因为它们用强悍的词汇保护贫弱的思想；而学会分辨诚实的困难与装饰性的困难，本身就是这门纪律的一部分。诚实的困难会偿还你的每一个小时：那个迟到了三章才终于自行组装完成的论证，抵达时携带着任何摘要都无法承载的力量——恰恰因为它走过的路是你亲手修建的。"),
 ("So I keep a shelf of books that have defeated me, and I return to it the way climbers return to a mountain that turned them back. Some will defeat me again. But every few years, one of them quietly opens, and I am reminded that the border of the readable is not fixed; it moves outward exactly as far as we are willing to push it, and each book that opens makes the next one on the shelf look a little less impossible than it did before.",
  "所以我专门留了一格书架，放那些曾经打败过我的书，并像登山者重返曾把自己劝退的山峰那样回到它面前。有些书会再次打败我。但每隔几年，其中一本会悄然敞开。它提醒我：可读性的边界并非固定——我们愿意推多远，它就向外移多远；而每一本敞开的书，都会让书架上的下一本看起来不再那么高不可攀。"),
]),
]
