# Authored everyday English sentences: cet6 + postgraduate + toefl_ielts.

CET6 = [
    # short
    ("The committee approved the budget without further debate.", "委员会未经进一步讨论就批准了预算。"),
    ("Remote work has transformed how teams communicate.", "远程办公改变了团队的沟通方式。"),
    ("Her argument sounded strong but had little solid evidence.", "她的论点听起来有力，但缺乏可靠的证据。"),
    ("The company launched an investigation into the complaint.", "公司针对这起投诉展开了调查。"),
    ("House prices outside the city continue to rise.", "城外的房价持续上涨。"),
    ("He negotiated a better contract with the supplier.", "他和供应商谈成了一份更好的合同。"),
    ("The article analyzes recent trends in consumer behavior.", "这篇文章分析了消费者行为的最新趋势。"),
    ("Their new company received investment from several firms.", "他们的新公司获得了几家公司的投资。"),
    ("The new regulation takes effect at the start of July.", "新规定七月初开始生效。"),
    ("She deals with customer complaints in a calm and patient way.", "她以冷静耐心的方式处理顾客投诉。"),
    ("The data suggests a gradual shift in public opinion.", "数据表明公众舆论正在逐渐转变。"),
    ("Volunteers distributed supplies to the affected families.", "志愿者向受灾家庭分发了物资。"),
    ("The lecture examined the causes of urban poverty.", "讲座探讨了城市贫困的成因。"),
    ("His proposal was rejected due to budget concerns.", "他的提案因预算问题被否决了。"),
    ("The airline upgraded my seat without extra charge.", "航空公司免费给我升了舱。"),
    ("Researchers observed a significant drop in pollution levels.", "研究人员观察到污染水平显著下降。"),
    ("The museum digitized thousands of historical documents.", "博物馆将数千份历史文件数字化了。"),
    ("Sales figures exceeded expectations in the third quarter.", "第三季度的销售数据超出了预期。"),
    ("The union asked for better and safe conditions for factory workers.", "工会要求为工厂工人提供更好且安全的工作条件。"),
    ("Critics liked the film because it tells an honest story.", "影评人喜欢这部电影，因为它讲述了一个真诚的故事。"),
    ("The app collects feedback through short weekly surveys.", "这款应用通过每周简短的问卷收集反馈。"),
    ("A balanced diet contributes to long-term health.", "均衡的饮食有益于长期健康。"),
    ("The bank tightened its requirements for personal loans.", "银行收紧了个人贷款的要求。"),
    ("Their research team published the findings last month.", "他们的研究团队上个月发表了这些发现。"),
    # medium
    ("The government announced a new program to support small businesses struggling with rising costs.", "政府宣布了一项新计划，扶持艰难应对成本上涨的小企业。"),
    ("Despite the initial criticism, the updated design proved far more practical for daily use.", "尽管最初受到批评，更新后的设计被证明在日常使用中实用得多。"),
    ("The study found that students who sleep well generally perform better on difficult exams.", "研究发现，睡眠充足的学生在难度大的考试中通常表现更好。"),
    ("Our department is seeking candidates with strong communication skills and relevant project experience.", "我们部门正在寻找沟通能力强并具有相关项目经验的候选人。"),
    ("The documentary explores how a small fishing village adapted to dramatic environmental changes.", "这部纪录片探讨了一个小渔村如何适应剧烈的环境变化。"),
    ("He admitted that the schedule was too ambitious and agreed to extend the deadline.", "他承认日程安排过于激进，并同意延长截止日期。"),
    ("The conference brought together experts from different fields to discuss sustainable city planning.", "这次会议汇聚了不同领域的专家，共同探讨可持续的城市规划。"),
    ("Online reviews influence purchasing decisions far more than traditional advertising does today.", "如今网上评价对购买决策的影响远超传统广告。"),
    ("The hospital introduced an electronic system to reduce errors in patient records.", "医院引入了电子系统，以减少病历中的错误。"),
    ("Many graduates struggle to find affordable housing in cities where the best jobs are located.", "许多毕业生很难在好工作集中的城市找到负担得起的住房。"),
    ("The author argues that technology should serve human needs rather than replace human judgment.", "作者认为技术应当服务于人的需求，而不是取代人的判断。"),
    ("Employees are encouraged to report safety issues without fear of negative consequences.", "公司鼓励员工报告安全问题，而不必担心负面后果。"),
    ("The charity depends mainly on monthly gifts from a small group of faithful members.", "这家慈善机构主要依靠一小群忠实成员的每月捐赠。"),
    ("After reviewing the evidence, the committee concluded that the original decision was fair.", "审查证据后，委员会得出结论，原来的决定是公正的。"),
    ("The rapid growth of food delivery services has changed the restaurant industry permanently.", "外卖服务的迅速发展永久地改变了餐饮业。"),
    ("She balanced her full-time job with evening classes to earn a degree in accounting.", "她一边做全职工作，一边上夜校，攻读会计学位。"),
    ("The negotiation failed because neither side was willing to compromise on the key issues.", "谈判失败了，因为双方都不愿在关键问题上让步。"),
    ("Public libraries are expanding their digital collections to meet changing reader habits.", "公共图书馆正在扩充数字馆藏，以适应读者习惯的变化。"),
    ("The survey revealed that most residents support the plan to expand the subway network.", "调查显示，大多数居民支持扩建地铁网络的计划。"),
    ("Climate experts warn that extreme weather events are becoming more frequent and severe.", "气候专家警告说，极端天气事件正变得越来越频繁和严重。"),
    ("The firm offers flexible schedules to help employees balance work and family responsibilities.", "公司提供弹性工作时间，帮助员工平衡工作和家庭责任。"),
    ("His latest book examines the hidden costs of convenience in the digital economy.", "他的新书审视了数字经济中便利背后的隐性代价。"),
    ("The committee will evaluate each application based on merit rather than personal connections.", "委员会将根据能力而非人脉来评估每份申请。"),
    ("Renewable energy now accounts for a growing share of the country's electricity production.", "可再生能源在该国发电量中所占的比例越来越大。"),
    # long
    ("The report concludes that investing in public transportation not only reduces traffic congestion but also improves air quality and creates thousands of stable jobs for local communities.", "报告的结论是，投资公共交通不仅能缓解交通拥堵，还能改善空气质量，并为当地社区创造数千个稳定的工作岗位。"),
    ("Although electric cars are becoming more affordable every year, many drivers still hesitate to switch because charging stations remain scarce outside the major cities.", "尽管电动汽车一年比一年便宜，许多司机仍对换车犹豫不决，因为大城市以外的充电站仍然稀缺。"),
    ("The university decided to record all introductory lectures and make them freely available online, allowing students to review difficult concepts at their own pace.", "大学决定录制所有入门课程并免费放到网上，让学生能按自己的节奏复习难懂的概念。"),
    ("When the factory announced it would close at the end of the year, the city offered tax breaks to attract new employers and retrain the affected workers.", "工厂宣布将于年底关闭后，市政府提供税收优惠以吸引新雇主，并对受影响的工人进行再培训。"),
    ("The research team spent three years following five hundred families to understand how early reading habits influence children's performance throughout primary school.", "研究团队花了三年时间跟踪五百个家庭，以了解早期阅读习惯如何影响孩子整个小学阶段的表现。"),
    ("Critics of the new policy argue that it places too heavy a burden on small businesses while offering little protection to the workers it claims to help.", "新政策的批评者认为，它给小企业带来了过重的负担，却几乎没有为它声称要帮助的工人提供保护。"),
    ("The exhibition combines photographs, letters, and recorded interviews to tell the story of the families who rebuilt the neighborhood after the flood.", "展览通过照片、书信和访谈录音，讲述了洪水过后重建社区的家庭的故事。"),
    ("As more people choose to work remotely, smaller towns with good internet and affordable housing are experiencing population growth for the first time in decades.", "随着越来越多的人选择远程工作，拥有良好网络和低价住房的小城镇几十年来首次出现人口增长。"),
    ("The airline said sorry for the long delay and offered free meals, hotel rooms, and a full refund for those who chose to cancel.", "航空公司为长时间延误道歉，提供免费餐食和酒店房间，选择取消行程的乘客可获全额退款。"),
    ("Her thesis examines how social media platforms shape political discussion, drawing on interviews with users from three very different age groups.", "她的论文研究社交媒体平台如何塑造政治讨论，依据的是对三个差异很大的年龄群体用户的访谈。"),
    ("The company's decision to replace plastic packaging with recycled paper increased costs slightly, but customer loyalty improved enough to justify the change.", "公司用再生纸取代塑料包装的决定让成本略有上升，但客户忠诚度的提升足以证明这一改变是值得的。"),
    ("Local farmers formed a cooperative to sell directly to city restaurants, cutting out middlemen and earning nearly twice what they received before.", "当地农民成立合作社，直接向城市餐厅供货，省去了中间商，收入几乎是以前的两倍。"),
    ("The committee recommended stricter inspections of older buildings after the survey revealed that many had not been checked in more than a decade.", "调查显示许多老旧建筑十多年未经检查，因此委员会建议对其进行更严格的检查。"),
    ("Despite years of warnings from engineers, the bridge repairs were repeatedly postponed until the city finally closed it to heavy vehicles last winter.", "尽管工程师们警告多年，大桥维修仍被一再推迟，直到去年冬天市政府终于禁止重型车辆通行。"),
    ("The program connects retired experts with young business owners, giving the new companies practical advice while letting the older generation share their experience.", "该项目让退休专家与年轻创业者建立联系，为新公司提供实用建议，也让老一辈得以分享经验。"),
    ("Researchers discovered that the ancient trading route stretched far beyond what historians had assumed, connecting communities across the entire region.", "研究人员发现，这条古代贸易路线的范围远超历史学家的设想，连接了整个地区的社群。"),
    ("The city's experiment with free public transport on weekends attracted so many visitors to the downtown shops that officials are considering extending it.", "该市周末免费公共交通的试验为市中心商铺吸引了大量顾客，官员们正考虑延长这一政策。"),
    ("After the documentary was shown on television, support for the wildlife park grew three times, allowing the staff to expand the rescue program and hire two animal doctors.", "纪录片在电视播出后，对野生动物园的支持增长了三倍，工作人员得以扩大救助项目并聘请两名兽医。"),
    ("The new management restructured the entire department, and although the process was painful, productivity and morale have clearly improved since then.", "新管理层重组了整个部门，虽然过程痛苦，但此后生产效率和士气明显提高。"),
    ("Economists disagree about the long-term effects of the policy, but most accept that it provided crucial relief to households during the crisis.", "经济学家对该政策的长期影响看法不一，但大多数人承认它在危机期间为家庭提供了关键的纾困。"),
    ("The startup's success came not from inventing new technology but from making existing tools simple enough for anyone to use without training.", "这家初创公司的成功并非源于发明新技术，而是把现有工具做得足够简单，任何人无需培训即可使用。"),
    ("The report urges schools to teach basic financial skills, noting that many young adults sign their first loan without understanding the interest terms.", "报告敦促学校教授基本的理财技能，并指出许多年轻人在签下第一笔贷款时并不理解利息条款。"),
    ("Following months of public consultation, the council revised the development plan to preserve the old market square and add more green space.", "经过数月的公众咨询，市政会修订了开发计划，保留老市场广场并增加更多绿地。"),
    ("The translation project recruited volunteers from twelve countries, and together they made the safety guidelines available in more than thirty languages.", "这个翻译项目招募了来自十二个国家的志愿者，他们一起把安全指南翻译成三十多种语言。"),
]

POSTGRADUATE = [
    # short
    ("The hypothesis was tested under controlled laboratory conditions.", "该假设在受控的实验室条件下得到了检验。"),
    ("Preliminary results indicate a strong correlation between the variables.", "初步结果表明这些变量之间存在很强的相关性。"),
    ("The methodology section requires substantial revision.", "方法论部分需要大幅修改。"),
    ("Funding constraints limited the scope of the experiment.", "经费限制缩小了实验的范围。"),
    ("Her dissertation challenges several established assumptions.", "她的博士论文挑战了几个既有假设。"),
    ("The findings were replicated by an independent team.", "这些发现已由一个独立团队重复验证。"),
    ("Peer review remains essential to academic publishing.", "同行评审仍然是学术出版的关键环节。"),
    ("The sample size was insufficient for reliable conclusions.", "样本量不足以得出可靠的结论。"),
    ("The committee doubted whether the framework was valid.", "委员会怀疑该框架是否有效。"),
    ("Recent advances have reshaped the entire discipline.", "近年的进展重塑了整个学科。"),
    ("The seminar addressed ethical issues in data collection.", "研讨会讨论了数据收集中的伦理问题。"),
    ("His analysis is based on archive sources from three countries.", "他的分析基于来自三个国家的档案资料。"),
    ("The grant covers fieldwork expenses for two years.", "该基金涵盖两年的田野调查费用。"),
    ("The theory fails to account for regional variation.", "该理论无法解释地区差异。"),
    ("Cooperation across fields made the research design much richer.", "跨领域合作大大丰富了研究设计。"),
    ("The journal rejected the paper after the second review.", "第二轮评审后，期刊拒绝了这篇论文。"),
    ("Their model can predict outcomes with unusual accuracy.", "他们的模型能以异乎寻常的准确度预测结果。"),
    ("The survey instrument was validated in a pilot study.", "调查工具在一项预实验中得到了验证。"),
    ("Statistical significance does not guarantee practical relevance.", "统计显著性并不保证实际意义。"),
    ("The conference deadline has been extended by two weeks.", "会议截稿日期延长了两周。"),
    ("She presented her preliminary findings at the symposium.", "她在研讨会上展示了初步研究结果。"),
    ("The literature review exposed a significant research gap.", "文献综述揭示了一个重要的研究空白。"),
    ("Access to the archive requires prior written approval.", "查阅该档案需要事先获得书面批准。"),
    ("The revised manuscript was accepted for publication.", "修改后的稿件被接收发表了。"),
    # medium
    ("The supervisor suggested narrowing the research question to make the project feasible within one year.", "导师建议缩小研究问题的范围，使项目能在一年内完成。"),
    ("Participants were randomly assigned to two groups to eliminate potential bias in the comparison.", "参与者被随机分为两组，以消除比较中可能存在的偏差。"),
    ("The findings imply that policy interventions are most effective when introduced at an early stage.", "研究结果表明，政策干预在早期引入时效果最佳。"),
    ("Critics argue that the model oversimplifies the complex relationship between income and well-being.", "批评者认为该模型过度简化了收入与幸福感之间的复杂关系。"),
    ("The author admits the limits of the data but stands by the overall conclusions.", "作者承认数据的局限，但坚持总体结论。"),
    ("Securing ethical approval took longer than expected, which delayed the start of the interviews.", "获得伦理审批的时间比预期长，推迟了访谈的开始。"),
    ("The results contradict earlier studies, suggesting that the effect may depend on cultural context.", "这些结果与早期研究相矛盾，表明该效应可能取决于文化背景。"),
    ("A growing body of evidence links urban green space to measurable improvements in mental health.", "越来越多的证据表明，城市绿地与心理健康的可测量改善相关。"),
    ("The panel emphasized that reproducibility should be a basic requirement for all published research.", "专家组强调，可重复性应当成为所有发表研究的基本要求。"),
    ("Her comparative study examines how different legal systems respond to the same economic pressures.", "她的比较研究考察了不同法律体系如何应对相同的经济压力。"),
    ("The university established a new center to coordinate research on aging and public health.", "大学成立了一个新中心，统筹老龄化与公共卫生方面的研究。"),
    ("Despite extensive documentation, the historical record remains silent on several crucial details.", "尽管文献丰富，历史记录在几个关键细节上仍然空白。"),
    ("The simulation demonstrates how small policy changes can produce large effects over several decades.", "模拟显示了微小的政策变化如何在几十年间产生巨大影响。"),
    ("Interviews with former employees revealed patterns that the official reports had carefully avoided.", "对前员工的访谈揭示了官方报告刻意回避的模式。"),
    ("The framework integrates insights from economics, psychology, and computer science.", "该框架整合了经济学、心理学和计算机科学的见解。"),
    ("Researchers must balance the demand for transparency with the obligation to protect participants' privacy.", "研究者必须在透明度要求与保护参与者隐私的义务之间取得平衡。"),
    ("The committee recommended that the laboratory adopt stricter protocols for storing sensitive samples.", "委员会建议实验室采用更严格的敏感样本存储规程。"),
    ("His argument rests on the assumption that institutions adapt slowly to technological change.", "他的论证基于一个假设：制度对技术变革的适应是缓慢的。"),
    ("The dataset spans twenty years and covers every registered hospital in the region.", "该数据集跨越二十年，覆盖该地区所有注册医院。"),
    ("The workshop helped research students learn to explain their findings to the general public.", "工作坊帮助研究生学会向公众解释他们的研究发现。"),
    ("Recent fieldwork suggests that the migration patterns are more seasonal than previously believed.", "最近的田野调查表明，迁徙模式比以前认为的更具季节性。"),
    ("The reviewers asked for additional experiments to support the central claim of the paper.", "审稿人要求补充实验来支持论文的核心主张。"),
    ("Funding agencies increasingly require that data be shared openly once the project concludes.", "资助机构越来越多地要求项目结束后公开共享数据。"),
    ("The study controls for education and income to isolate the effect of neighborhood environment.", "该研究控制了教育和收入变量，以分离社区环境的影响。"),
    # long
    ("The longitudinal study tracked two thousand participants over fifteen years and found that early access to quality education had lasting effects on income, health, and civic engagement.", "这项纵向研究对两千名参与者进行了十五年的跟踪，发现早期接受优质教育对收入、健康和公民参与有持久影响。"),
    ("Although the theoretical model elegantly explains the laboratory results, applying it to real markets requires assumptions that many economists consider unrealistic.", "尽管该理论模型能优雅地解释实验室结果，但将其应用于真实市场需要许多经济学家认为不切实际的假设。"),
    ("The research consortium agreed to standardize their measurement procedures so that results from laboratories in different countries could be compared directly.", "研究联盟同意统一测量程序，使不同国家实验室的结果可以直接比较。"),
    ("After the initial submission was rejected, the authors redesigned the experiment, doubled the sample size, and eventually published the work in a leading journal.", "初次投稿被拒后，作者重新设计了实验，将样本量扩大一倍，最终在一家顶级期刊上发表了该研究。"),
    ("The seminar series invites scholars whose work crosses disciplinary boundaries, on the theory that the most interesting questions arise where established fields meet.", "该系列研讨会邀请研究跨越学科边界的学者，其理念是最有趣的问题往往出现在既有领域的交汇处。"),
    ("Critics of the ranking system argue that it rewards quantity over quality and pressures young researchers to publish fragments rather than complete, careful studies.", "排名体系的批评者认为它重数量轻质量，迫使年轻研究者发表零碎成果而非完整严谨的研究。"),
    ("The archive contains thousands of letters that have never been systematically studied, offering researchers a rare window into the daily concerns of ordinary families.", "该档案馆收藏了数千封从未被系统研究过的书信，为研究者提供了了解普通家庭日常关切的难得窗口。"),
    ("By combining satellite imagery with household surveys, the team was able to estimate economic activity in regions where official statistics are unreliable or missing.", "通过将卫星图像与住户调查相结合，团队得以估算官方统计不可靠或缺失地区的经济活动。"),
    ("The ethics board required the researchers to revise their consent procedures after concerns were raised about how the study had been explained to elderly participants.", "在有人对研究向老年参与者的解释方式提出担忧后，伦理委员会要求研究者修改知情同意程序。"),
    ("Early excitement about the technique cooled after independent laboratories failed again and again to repeat the original findings under the same conditions.", "当独立实验室在相同条件下一再无法重复原始结果后，人们对该技术最初的兴奋逐渐冷却。"),
    ("The thesis suggests that the reform worked not because of its design but because local officials adjusted it in silence to fit existing practice.", "该论文提出，改革奏效并非因为其设计，而是因为地方官员默默调整了它以适应现有做法。"),
    ("Large language models raise difficult questions about authorship and originality that the current peer review system was never designed to handle.", "大型语言模型引发了关于作者身份和原创性的难题，而现行同行评审制度从未为处理这些问题而设计。"),
    ("The international team assembled a database of coastal measurements going back a century, which now serves as the standard reference for studying sea level change.", "国际团队汇编了一个回溯百年的海岸测量数据库，如今已成为研究海平面变化的标准参考。"),
    ("Repeat studies in psychology have pushed the field to reform its methods, including registering each hypothesis in advance and openly sharing raw data and analysis code.", "心理学领域的重复研究推动了方法改革，包括提前注册每个假设以及公开共享原始数据和分析代码。"),
    ("The grant proposal must demonstrate not only scientific merit but also a credible plan for training students and communicating results to the public.", "基金申请书不仅要证明科学价值，还要提出培养学生和向公众传播成果的可信计划。"),
    ("Using court records and personal papers, the scholar shows how ordinary citizens lived through and pushed back against the great legal changes of the period.", "这位学者利用法庭记录和私人文件，展示了普通公民如何经历并抵制那个时期的重大法律变革。"),
    ("The model performed well on historical data, yet the authors caution that structural changes in the economy may limit its usefulness for long-term forecasting.", "该模型在历史数据上表现良好，但作者提醒，经济结构的变化可能限制其在长期预测中的作用。"),
    ("Interviews conducted over three years reveal how the meaning of the reform shifted as different groups reinterpreted it to serve their own interests.", "历时三年的访谈揭示了改革的含义如何随着不同群体为自身利益重新诠释而发生变化。"),
    ("The laboratory's culture of carefully recording failed experiments proved invaluable when a routine result later turned out to depend on an overlooked variable.", "实验室认真记录失败实验的传统后来被证明极其宝贵——一个常规结果最终被发现取决于一个被忽视的变量。"),
    ("Scholars continue to debate whether the observed decline in trust reflects genuine social change or merely changes in how surveys ask the question.", "学者们仍在争论：观察到的信任度下降究竟反映了真实的社会变化，还是仅仅源于调查提问方式的变化。"),
    ("The university's decision to make all doctoral theses freely available online dramatically increased their citation rates within just a few years.", "大学决定将所有博士论文免费放到网上，短短几年内论文引用率大幅上升。"),
    ("A careful second analysis showed that the famous effect was gone once the researchers allowed for differences in how each region reported its statistics.", "仔细的二次分析表明，一旦研究者考虑各地区统计上报方式的差异，那个著名的效应便不复存在。"),
    ("The fellowship program deliberately places engineers in policy institutions, hoping that technical expertise will inform regulation before crises occur, not after.", "该奖学金项目特意把工程师安排到政策机构，希望技术专长能在危机发生之前而非之后影响监管。"),
    ("What began as a side note in her master's thesis eventually grew into a decade-long research program with partners on four continents.", "最初只是她硕士论文中的一个旁注，最终发展成一个有四大洲伙伴参与的十年研究计划。"),
]

TOEFL_IELTS = [
    # short
    ("Urbanization has accelerated dramatically across the developing world.", "城市化在发展中国家急剧加速。"),
    ("The professor's sharp criticism shook the most widely accepted theory.", "教授尖锐的批评动摇了最被广泛接受的理论。"),
    ("The steady loss of species brings risks that nature cannot reverse.", "物种的持续消失带来大自然无法逆转的风险。"),
    ("The talks broke down despite months of careful and quiet effort.", "尽管经过数月谨慎而低调的努力，会谈还是破裂了。"),
    ("Genetic factors partially explain individual differences in longevity.", "遗传因素部分解释了个体寿命的差异。"),
    ("The exhibition juxtaposes classical sculpture with contemporary installations.", "展览将古典雕塑与当代装置艺术并置。"),
    ("Automation will certainly transform the global labor market.", "自动化必将改变全球劳动力市场。"),
    ("Her findings contradict the conventional wisdom on motivation.", "她的发现与关于动机的传统观念相矛盾。"),
    ("The new law brings much heavier penalties for industrial pollution.", "新法律对工业污染处以重得多的处罚。"),
    ("Coral is extremely sensitive to small changes in sea temperature.", "珊瑚对海水温度的微小变化极为敏感。"),
    ("The author uses sharp humor to expose social pretense.", "作者用犀利的幽默揭露社会的虚伪。"),
    ("Compulsory voting remains a controversial policy worldwide.", "强制投票在世界范围内仍是一项有争议的政策。"),
    ("The committee unanimously endorsed the revised proposal.", "委员会一致支持修订后的提案。"),
    ("Language diversity is falling at a speed that should alarm us.", "语言多样性正以令人警觉的速度减少。"),
    ("The court decision set an important example for future law.", "这一法院判决为未来的法律树立了重要先例。"),
    ("Too much screen time is closely linked with poor sleep patterns.", "屏幕时间过长与糟糕的睡眠模式密切相关。"),
    ("The theory brings two competing explanations together with rare grace.", "该理论以罕见的优雅将两种相互竞争的解释统一起来。"),
    ("Migration policy dominated the parliamentary debate yesterday.", "移民政策主导了昨天的议会辩论。"),
    ("The vaccine demonstrated remarkable efficacy in clinical trials.", "该疫苗在临床试验中显示出显著的效力。"),
    ("Researchers dug up objects far older than the earliest written records.", "研究人员挖掘出远早于最早文字记录的物品。"),
    ("The documentary scrutinizes the ethics of wildlife tourism.", "这部纪录片审视了野生动物旅游的伦理问题。"),
    ("Monetary policy alone cannot resolve structural unemployment.", "仅靠货币政策无法解决结构性失业。"),
    ("The mountain ice has clearly drawn back within a single generation.", "仅一代人的时间，山上的冰川就明显退缩了。"),
    ("Bias built into software can deepen the gaps that already divide society.", "内嵌于软件的偏见会加深已经分裂社会的鸿沟。"),
    # medium
    ("The lecture examined how colonial trade networks permanently altered agricultural practices on three continents.", "讲座探讨了殖民贸易网络如何永久改变了三大洲的农业实践。"),
    ("Supporters of the carbon tax argue that market rewards work better than direct rules in cutting emissions.", "碳税的支持者认为，在减排方面市场激励比直接管制更有效。"),
    ("The study demonstrates that bilingual children switch between tasks more efficiently than their monolingual peers.", "研究表明，双语儿童在任务间切换的效率高于单语同龄人。"),
    ("Skeptics question whether the announced reforms will survive the inevitable resistance from entrenched interests.", "怀疑者质疑已宣布的改革能否经受住既得利益集团不可避免的抵制。"),
    ("The novel interweaves three generations of family history with the political upheavals of the twentieth century.", "这部小说将三代家族史与二十世纪的政治动荡交织在一起。"),
    ("Satellite data shows that forest loss has sped up despite international promises to stop it.", "卫星数据显示，尽管国际社会承诺制止，森林消失的速度仍在加快。"),
    ("The university faces mounting criticism for prioritizing commercial partnerships over academic independence.", "该大学因将商业合作置于学术独立之上而面临越来越多的批评。"),
    ("Behavioral economists attribute the savings gap to present bias rather than simple lack of discipline.", "行为经济学家将储蓄缺口归因于现时偏好，而非单纯缺乏自律。"),
    ("The tribunal ruled that the company had knowingly concealed environmental risks from investors and regulators.", "法庭裁定该公司故意向投资者和监管机构隐瞒环境风险。"),
    ("Its defenders claim that universal basic income would free workers to pursue education and start new businesses.", "其拥护者声称，全民基本收入将使劳动者能够自由地接受教育和创业。"),
    ("The findings suggest that memory consolidation depends critically on the quality of sleep following learning.", "研究结果表明，记忆巩固在很大程度上取决于学习后的睡眠质量。"),
    ("Historians caution against interpreting ancient texts through the moral framework of the present day.", "历史学家告诫不要用当今的道德框架解读古代文本。"),
    ("The infrastructure bill stopped moving in parliament as rival groups argued over how to divide the costs.", "由于对立派别就成本分摊争执不下，基础设施法案在议会停滞不前。"),
    ("Ocean scientists recorded unknown species living in rich numbers around hot openings in the deep sea floor.", "海洋科学家记录了在深海热泉口周围大量生存的未知物种。"),
    ("The new curriculum values critical thinking above the memory of isolated facts.", "新课程重视批判性思维，而非对孤立事实的记忆。"),
    ("Experts warn that a long trade war could break global supply chains beyond repair.", "专家警告，旷日持久的贸易战可能使全球供应链断裂到无法修复。"),
    ("The exhibition follows the artist's journey from realistic painting to pure abstract art.", "展览追溯了这位艺术家从写实绘画到纯抽象艺术的历程。"),
    ("Urban planners increasingly favor mixed-use districts that integrate housing, commerce, and public space.", "城市规划者越来越青睐融合住宅、商业和公共空间的混合功能街区。"),
    ("The investigation exposed systematic discrepancies between the reported and actual emissions figures.", "调查揭露了上报排放数据与实际数据之间的系统性差异。"),
    ("Psychology separates brief pleasure from the deeper satisfaction that comes from work with purpose.", "心理学区分了短暂的快乐与源于有目标的工作的更深层满足。"),
    ("The long dry season destroyed crops across the region, driving food prices to record levels.", "漫长的旱季摧毁了该地区的庄稼，将粮价推至创纪录的水平。"),
    ("Those who defend the humanities argue that literature builds understanding of others in ways no other field can.", "人文学科的捍卫者认为，文学以其他领域无法替代的方式培养对他人的理解。"),
    ("The merger raises antitrust concerns because the combined firm would control most of the regional market.", "这桩并购引发了反垄断担忧，因为合并后的公司将控制该地区大部分市场。"),
    ("The loss of mountain ice puts at risk the water supply of communities that depend on it to water their fields.", "山地冰川的消失威胁着依赖其灌溉农田的社区的供水。"),
    # long
    ("The committee's report argues that without coordinated international action on carbon pricing, individual national efforts will merely shift emissions across borders rather than reduce them globally.", "委员会的报告认为，如果没有在碳定价上协调一致的国际行动，各国单独的努力只会让排放跨境转移，而非在全球范围内减少。"),
    ("Whereas earlier generations of automation displaced primarily manual labor, current artificial intelligence systems increasingly perform analytical tasks once considered the exclusive domain of educated professionals.", "早期的自动化主要取代体力劳动，而当前的人工智能系统正越来越多地执行曾被视为受过教育的专业人士专属领域的分析性工作。"),
    ("The longitudinal data demonstrate that children who grow up in linguistically rich environments develop larger vocabularies and stronger reasoning skills, regardless of their family's economic circumstances.", "纵向数据表明，在语言环境丰富中成长的孩子词汇量更大、推理能力更强，无论其家庭经济状况如何。"),
    ("Critics of standardized testing maintain that it narrows the curriculum and rewards test-taking strategies, while supporters counter that it remains the only objective measure available at scale.", "标准化考试的批评者坚持认为它窄化了课程并奖励应试技巧，而支持者反驳说它仍是唯一可大规模使用的客观衡量标准。"),
    ("The excavation revealed that the settlement had been rebuilt at least four times, each layer reflecting the materials, techniques, and trade connections of a different era.", "发掘显示该定居点至少重建过四次，每一地层都反映了不同时代的材料、工艺和贸易联系。"),
    ("Although renewable sources now generate a substantial portion of the nation's electricity, storage limitations mean that fossil fuel plants must still operate as backup during periods of peak demand.", "尽管可再生能源现在提供了全国相当一部分电力，但储能的限制意味着化石燃料电厂在需求高峰期仍须作为备用运行。"),
    ("The ruling reflects a broader judicial trend toward holding technology platforms accountable for the foreseeable consequences of their design choices, not merely for the content users post.", "这一判决反映了更广泛的司法趋势：让技术平台为其设计选择的可预见后果负责，而不仅仅是为用户发布的内容负责。"),
    ("By analyzing shipping records, tax registers, and personal correspondence, the historian reconstructs the hidden networks through which credit flowed in early modern Mediterranean commerce.", "通过分析航运记录、税册和私人信件，这位历史学家重构了近代早期地中海商业中信贷流动的隐秘网络。"),
    ("The pandemic exposed how dependent global manufacturing had become on a handful of specialized suppliers, prompting governments to subsidize domestic production of critical components.", "疫情暴露了全球制造业对少数专业供应商的依赖程度，促使各国政府补贴关键零部件的国内生产。"),
    ("Supporters argue that bringing back large wild animals produces a chain of natural benefits, although farmers and rural communities remain careful about the policy for good reason.", "支持者认为让大型野生动物回归会产生一连串自然效益，尽管农民和乡村社区对这一政策保持谨慎也是有道理的。"),
    ("The study tracked graduates for two decades and concluded that the prestige of the university mattered far less for long-term success than the field of study and early work experience.", "这项研究对毕业生进行了二十年的跟踪，结论是大学的声望对长期成功的影响远小于所学专业和早期工作经验。"),
    ("Nature protection faces a hard choice: the tourism that pays for saving wild places also brings noise, waste, and pressure into those same fragile systems.", "自然保护面临艰难抉择：为保护荒野买单的旅游业，同时也把噪音、垃圾和压力带进了这些脆弱的系统。"),
    ("The author contends that the decline of local journalism has weakened civic accountability, as city councils and school boards now operate with far less public scrutiny than a generation ago.", "作者认为地方新闻业的衰落削弱了公民问责，如今市议会和学校董事会受到的公众监督远少于上一代人的时代。"),
    ("Progress in gene editing has moved faster than the rules meant to govern it, leaving scientists and lawmakers struggling to define acceptable limits.", "基因编辑的进展快于旨在管理它的规则，使科学家和立法者都在艰难界定可接受的界限。"),
    ("The negotiations ultimately failed because the parties could not agree on verification mechanisms, each side fearing that the other would exploit any ambiguity in the inspection protocols.", "谈判最终失败，因为各方无法就核查机制达成一致，每一方都担心对方会利用核查程序中的任何模糊之处。"),
    ("What distinguishes the current wave of urbanization from earlier episodes is its speed: cities in some regions are absorbing populations in decades that European cities absorbed over centuries.", "当前城市化浪潮与以往的区别在于速度：某些地区的城市在几十年内吸纳的人口，相当于欧洲城市几个世纪的总量。"),
    ("The meta-analysis pooled results from ninety clinical trials and found that the treatment's benefits, while statistically robust, were too small to justify its considerable cost and side effects.", "这项荟萃分析汇集了九十项临床试验的结果，发现该疗法的益处虽然在统计上稳健，但太小，不足以抵偿其高昂成本和副作用。"),
    ("Linguists studying endangered languages race against time to document grammatical structures that, once lost, can never be recovered and may hold clues to the limits of human cognition.", "研究濒危语言的语言学家与时间赛跑，记录那些一旦消失便无法恢复的语法结构——它们可能蕴含着人类认知极限的线索。"),
    ("The inquiry concluded that the power failure came not from one big error but from a chain of small problems, each easy to handle alone, combining in ways no operator had expected.", "调查的结论是，停电并非源于单个重大错误，而是一连串小问题——每个单独看都容易处理——以无人预料的方式叠加所致。"),
    ("Far from being passive victims of globalization, the artisans documented in this ethnography actively reinterpret traditional crafts to appeal to international markets on their own terms.", "这部民族志记录的手工艺人远非全球化的被动受害者，他们主动重新诠释传统工艺，以自己的方式吸引国际市场。"),
    ("The proposal to mine the seabed divides scientists: some see essential minerals for the energy transition, while others warn of destroying ecosystems we have barely begun to understand.", "海底采矿的提议让科学家们意见分裂：一些人看到了能源转型所需的关键矿物，另一些人则警告这会摧毁我们才刚刚开始了解的生态系统。"),
    ("Reflecting on the failed reform, the minister admitted that the government had underestimated how deeply the existing system was woven into the daily routines of millions of households.", "反思失败的改革时，部长承认政府低估了现行制度与千百万家庭日常生活交织的深度。"),
    ("The observatory's data archive, built with patience over half a century, proved decisive in confirming a deep physical effect that theory had predicted but no one had observed.", "天文台耐心积累了半个世纪的数据档案，对证实理论预言却无人观测到的深层物理效应起了决定性作用。"),
    ("Whether the city's experiment in letting residents direct public spending truly shifts power, or merely dresses up decisions already made elsewhere, remains a matter of heated academic debate.", "该市让居民支配公共开支的试验究竟是真正转移了权力，还是只为别处已做的决定披上外衣，仍是学界激烈争论的问题。"),
]
