# Authored everyday English sentences: high_school + cet4 (modern daily life).
# Each tuple: (text, translation_zh). Length class derived from word count.

HIGH_SCHOOL = [
    # short (6-12 words)
    ("Can you send me the photo later?", "你晚点能把照片发给我吗？"),
    ("I left my keys on the kitchen table.", "我把钥匙落在厨房桌上了。"),
    ("Let's meet at the coffee shop at three.", "我们三点在咖啡店见吧。"),
    ("The bus was late again this morning.", "今天早上公交车又晚点了。"),
    ("She likes to cook dinner with her father.", "她喜欢和爸爸一起做晚饭。"),
    ("Please turn off the lights before you leave.", "离开前请把灯关掉。"),
    ("My phone battery is almost dead.", "我手机快没电了。"),
    ("We watched a funny movie last night.", "我们昨晚看了一部很好笑的电影。"),
    ("Do you want some milk in your tea?", "你的茶里要加点牛奶吗？"),
    ("He walks his dog in the park every day.", "他每天都在公园里遛狗。"),
    ("The store is open until nine every day.", "这家店每天营业到九点。"),
    ("I need to buy a gift for my friend.", "我需要给朋友买份礼物。"),
    ("It looks like it will rain this afternoon.", "看起来今天下午要下雨。"),
    ("Could you open the window a little bit?", "你能把窗户开一点吗？"),
    ("They are moving to a new house next week.", "他们下周要搬进新房子。"),
    ("This food has a little too much salt for me.", "这食物对我来说盐放得有点多。"),
    ("Don't forget to bring your water bottle.", "别忘了带上你的水瓶。"),
    ("The train station is ten minutes from here.", "火车站离这里十分钟路程。"),
    ("I usually get up at seven on school days.", "上学的日子我通常七点起床。"),
    ("Her little brother is learning to ride a bike.", "她的弟弟正在学骑自行车。"),
    ("We had rice and fish for lunch today.", "我们今天午饭吃了米饭和鱼。"),
    ("Can I use your phone for a minute?", "我能用一下你的手机吗？"),
    ("The weather is perfect for a walk today.", "今天的天气很适合散步。"),
    ("He scored two goals in the game yesterday.", "他在昨天的比赛中进了两个球。"),
    # medium (13-22 words)
    ("My mother asked me to pick up some bread on my way home from school.", "妈妈让我放学回家路上买点面包。"),
    ("We are planning a small party for my sister because she just finished her exams.", "我们打算给妹妹办个小派对，因为她刚考完试。"),
    ("The teacher said we should read the first two chapters before the next class.", "老师说我们应该在下节课前读完前两章。"),
    ("I tried to call you twice last night, but your phone was turned off.", "昨晚我给你打了两次电话，但你的手机关机了。"),
    ("If the weather is nice on Saturday, we can ride our bikes to the lake.", "如果周六天气好，我们可以骑车去湖边。"),
    ("She keeps a small notebook to write down new words she learns every day.", "她随身带个小本子，记下每天学到的新单词。"),
    ("The supermarket near our house is having a big sale on fruit this week.", "我们家附近的超市这周水果大减价。"),
    ("My grandfather likes to tell us stories about his life when he was young.", "爷爷喜欢给我们讲他年轻时的故事。"),
    ("Please remember to feed the cat and water the plants while we are away.", "我们不在的时候，请记得喂猫和浇花。"),
    ("It took us almost two hours to clean the whole apartment this morning.", "今天早上我们花了将近两个小时打扫整个公寓。"),
    ("He was so sleepy after practice that he went to bed right after dinner.", "训练后他太困了，吃完晚饭就上床睡觉了。"),
    ("The children built a small castle out of sand and were very proud of it.", "孩子们用沙子堆了一座小城堡，非常自豪。"),
    ("Could you help me carry these bags upstairs before you go out to play?", "你出去玩之前能帮我把这些袋子搬上楼吗？"),
    ("We missed the first ten minutes of the movie because of the heavy traffic.", "因为堵车，我们错过了电影的前十分钟。"),
    ("My best friend moved to another city, but we still talk online every weekend.", "我最好的朋友搬去了另一个城市，但我们每个周末还在网上聊天。"),
    ("The doctor told him to drink more water and get at least eight hours of sleep.", "医生让他多喝水，每天至少睡八个小时。"),
    ("I want to save some money this year so I can buy a new bicycle.", "我今年想存点钱，好买一辆新自行车。"),
    ("There is a new student in our class, and she comes from a small town.", "我们班来了个新同学，她来自一个小镇。"),
    ("Father fixed the broken chair in the garden while Mother cleaned the front door.", "爸爸修好了花园里坏掉的椅子，妈妈把前门擦干净了。"),
    ("You should bring an umbrella because the radio said it might rain later today.", "你应该带把伞，广播说今天晚些时候可能下雨。"),
    ("Our team practiced hard for weeks, so everyone was happy when we won.", "我们队努力训练了好几周，所以赢的时候大家都很开心。"),
    ("She turned off the television and went to bed because she had an early class.", "她关掉电视去睡觉了，因为第二天有早课。"),
    ("The library was so quiet that I could hear the clock ticking on the wall.", "图书馆安静得我能听到墙上钟表的滴答声。"),
    ("After dinner we played cards with our cousins until it was time to go home.", "晚饭后我们和表兄妹打牌，一直玩到该回家的时候。"),
    # long (23-35 words)
    ("When I got home from school, I found that my little sister had already finished her homework and was helping our mother set the table for dinner.", "我放学回家时，发现妹妹已经写完作业，正在帮妈妈摆桌子准备晚饭。"),
    ("My father showed me how to plant vegetables last spring, and this summer we got enough from the garden to share with everyone near our house.", "去年春天爸爸教我种菜，今年夏天我们从园子里收获的蔬菜多到可以分给家附近的每个人。"),
    ("The school trip was canceled because of the storm, so the teachers showed us a film in the hall and let us play games in the afternoon.", "学校的郊游因暴风雨取消了，所以老师们在礼堂给我们放了电影，下午还让我们玩游戏。"),
    ("Every Sunday morning my family walks to the market near the river, where we buy fresh vegetables and sometimes stop for hot noodles at a small shop.", "每个周日早上，我们全家步行去河边的市场买新鲜蔬菜，有时还会在一家小店停下来吃热面条。"),
    ("I was nervous about speaking in front of the whole class, but after the first minute I relaxed and even started to enjoy telling my story.", "在全班面前讲话让我很紧张，但开始一分钟后我就放松了，甚至开始享受讲自己的故事。"),
    ("My grandmother says that when she was a girl, the town had no bus at all, and she had to walk a long way to school in every season.", "奶奶说她小时候镇上根本没有公交车，无论什么季节她都得走很远的路去上学。"),
    ("We spent the whole afternoon looking for the cat, and in the end we found her sleeping quietly in a basket of clean clothes upstairs.", "我们找了一下午的猫，最后发现她正安静地睡在楼上一篮干净衣服里。"),
    ("The new sports center near our school has a swimming pool, two basketball courts, and a running track, so everyone wants to go there after class.", "我们学校附近新建的体育中心有游泳池、两个篮球场和一条跑道，所以大家放学后都想去那里。"),
    ("If you finish your homework before six, we can watch the football game together and order some chicken and rice from the place you like.", "如果你六点前写完作业，我们就可以一起看足球比赛，再从你喜欢的那家店点鸡肉和米饭。"),
    ("On the first day of the holiday, we put bread and fruit in a bag, took the early train to the sea, and played on the beach until the evening.", "假期第一天，我们把面包和水果装进包里，坐早班火车去海边，在沙滩上一直玩到傍晚。"),
    ("She practiced the piano every evening for a month, and when she finally played the song for her teacher, he smiled and clapped his hands.", "她每天晚上练一个小时钢琴，坚持了一个月，当她终于给老师弹那首曲子时，老师笑着鼓起掌来。"),
    ("The little shop on the corner sells the best ice cream in town, and in summer there is always a long line outside the door.", "街角的小店卖全城最好吃的冰淇淋，夏天门口总是排着长队。"),
    ("My brother lost his bus card on the way home, so he had to walk for an hour, and he was very hungry when he arrived.", "我哥哥在回家路上丢了公交卡，只好走了一个小时，到家时已经饿坏了。"),
    ("Our teacher asked each of us to bring one old book to class so that we could open a small library by the window.", "老师让我们每人带一本旧书到班里，这样我们就能在窗边开一个小图书角。"),
    ("It snowed all night, and in the morning the whole street was white, so the children ran outside to make a snowman before breakfast.", "雪下了一整夜，早上整条街都白了，孩子们早饭前就跑出去堆雪人。"),
    ("I wanted to make my mother happy on her birthday, so I got up early, washed the dishes, and made her favorite breakfast.", "我想在妈妈生日那天让她开心，所以早早起床洗了碗，还做了她最爱吃的早餐。"),
    ("The game was almost over when our team got the ball, and in the last minute we scored the goal that won the match.", "比赛快结束时我们队拿到了球，在最后一分钟打进了制胜一球。"),
    ("During the summer holiday I read three books, learned to swim a little better, and helped my uncle paint the fence around his garden.", "暑假期间我读了三本书，游泳学得更好了一点，还帮叔叔给他家花园的栅栏刷了漆。"),
    ("When the lights went out during the storm, we lit candles, sat together in the living room, and told stories until the power came back.", "暴风雨导致停电时，我们点上蜡烛，一起坐在客厅里讲故事，直到来电。"),
    ("He saved his pocket money for half a year because he wanted to buy a present for his mother instead of asking his father for help.", "他攒了半年零花钱，因为他想自己给妈妈买礼物，而不是向爸爸求助。"),
    ("The museum near the station is free on Friday afternoons, so our class is going there next week to see the old ships and maps.", "车站附近的博物馆周五下午免费开放，所以我们班下周要去那里看古船和地图。"),
    ("My cousin is staying with us this month, and every evening after dinner we play table tennis in the yard until it gets dark.", "我表弟这个月住在我们家，每天晚饭后我们都在院子里打乒乓球，直到天黑。"),
    ("She was afraid of dogs when she was small, but now she has a big friendly one that follows her everywhere she goes.", "她小时候怕狗，但现在养了一只友善的大狗，走到哪儿都跟着她。"),
    ("We planted a small tree in front of the house five years ago, and now it is tall enough to give us shade in summer.", "五年前我们在房前种了一棵小树，现在它已经高到能在夏天为我们遮荫了。"),
]

CET4 = [
    # short
    ("The meeting has been moved to Thursday morning.", "会议改到周四上午了。"),
    ("I finally finished my report at midnight.", "我终于在午夜写完了报告。"),
    ("She applied for a part-time job last week.", "她上周申请了一份兼职工作。"),
    ("The price of coffee here is quite reasonable.", "这里的咖啡价格相当合理。"),
    ("Please check your email before the class starts.", "上课前请查看你的邮箱。"),
    ("He often works late during the busy season.", "旺季的时候他经常加班到很晚。"),
    ("Our flight was delayed by almost two hours.", "我们的航班延误了将近两个小时。"),
    ("I'm trying to spend less time on my phone.", "我在努力减少看手机的时间。"),
    ("The new shopping center opens next month.", "新的购物中心下个月开业。"),
    ("Could you explain this question one more time?", "你能把这道题再讲一遍吗？"),
    ("They offered her a position in the sales team.", "他们给了她销售团队的一个职位。"),
    ("My laptop needs to be repaired again.", "我的笔记本电脑又得修了。"),
    ("We should book the tickets as early as possible.", "我们应该尽早订票。"),
    ("The lecture covered the history of modern art.", "这次讲座讲了现代艺术史。"),
    ("He gave up smoking for the sake of his health.", "为了健康他戒了烟。"),
    ("The hotel provides free breakfast for all guests.", "这家酒店为所有客人提供免费早餐。"),
    ("I prefer reading news online to buying newspapers.", "比起买报纸，我更喜欢在网上看新闻。"),
    ("Her presentation impressed everyone in the room.", "她的演讲给在场的所有人留下了深刻印象。"),
    ("The library extends its hours during exam weeks.", "考试周图书馆会延长开放时间。"),
    ("You can cancel the order within twenty-four hours.", "你可以在二十四小时内取消订单。"),
    ("This app helps me manage my daily expenses.", "这个应用帮我管理日常开支。"),
    ("The traffic downtown is very heavy on Friday nights.", "周五晚上市中心的交通非常拥堵。"),
    ("He helps at the animal center every weekend.", "他每个周末都在动物中心帮忙。"),
    ("The company plans to hire more engineers this year.", "公司计划今年招聘更多工程师。"),
    # medium
    ("I have to prepare a short speech for the welcome party at the end of the month.", "我得为月底的欢迎会准备一个简短的发言。"),
    ("The customer service agent promised that the package would arrive within three working days.", "客服人员承诺包裹会在三个工作日内送达。"),
    ("She decided to take an online course to improve her writing skills during the holiday.", "她决定假期上一门网课来提高写作能力。"),
    ("The restaurant was fully booked, so we ended up trying the new place across the street.", "那家餐厅订满了，所以我们最后去试了街对面的新店。"),
    ("If you want to join the gym, they are offering a discount for students this month.", "如果你想办健身房会员，他们这个月对学生有折扣。"),
    ("My roommate said we should share the housework instead of fighting about it every week.", "我室友说我们应该分担家务，而不是每周为此吵架。"),
    ("The manager asked everyone to submit their weekly reports before Friday afternoon.", "经理要求所有人在周五下午之前提交周报。"),
    ("It turns out that the noise upstairs was just my neighbor moving his furniture around.", "原来楼上的噪音只是邻居在挪家具。"),
    ("I compared several brands online before deciding which washing machine to buy.", "我在网上比较了几个品牌，才决定买哪台洗衣机。"),
    ("The doctor suggested that I take a break from running until my knee fully recovers.", "医生建议我暂停跑步，直到膝盖完全恢复。"),
    ("We were supposed to meet at the cinema, but he went to the wrong one by mistake.", "我们本来约好在电影院见面，但他错去了另一家。"),
    ("The university offers free counseling services to students who feel stressed during exams.", "大学为考试期间感到压力的学生提供免费心理咨询。"),
    ("My internet connection kept dropping during the video call, which was really annoying.", "视频通话时我的网络一直断，真的很烦人。"),
    ("They raised the rent again this year, so we are thinking about moving to a smaller place.", "今年房租又涨了，所以我们在考虑搬到小一点的地方。"),
    ("He spent the whole weekend fixing his car instead of coming to the picnic with us.", "他整个周末都在修车，没跟我们一起去野餐。"),
    ("The new policy allows employees to work from home two days a week.", "新政策允许员工每周在家办公两天。"),
    ("I always make a shopping list before going to the supermarket so I don't overspend.", "去超市前我总会列购物清单，以免超支。"),
    ("The staff on the plane helped me find space for my bags above the seat.", "机上工作人员帮我在座位上方找到了放包的空间。"),
    ("She has been saving part of her salary every month for a trip to Europe next year.", "她每个月都存下一部分工资，准备明年去欧洲旅行。"),
    ("The presentation went well, although I was extremely nervous at the beginning.", "演讲进行得很顺利，虽然一开始我特别紧张。"),
    ("Our professor encourages us to ask questions whenever we don't understand the material.", "教授鼓励我们一有不懂的地方就提问。"),
    ("The weather forecast says the temperature will drop sharply over the weekend.", "天气预报说周末气温会骤降。"),
    ("I removed the file by mistake, but my workmate had saved another copy.", "我误删了文件，但同事保存了另一份副本。"),
    ("The volunteers spent the morning cleaning up the beach and collected ten bags of trash.", "志愿者们花了一上午清理海滩，收集了十袋垃圾。"),
    # long
    ("After comparing the prices and reviews of several hotels, we finally chose one near the city center because it was close to the subway and included breakfast.", "比较了几家酒店的价格和评价后，我们最终选了市中心附近的一家，因为它离地铁近还含早餐。"),
    ("The training session this morning lasted longer than expected, so the team decided to order lunch to the office instead of going out to the restaurant.", "今天上午的培训比预期时间长，所以团队决定点外卖到办公室，而不是出去下馆子。"),
    ("When my computer suddenly stopped working the night before the deadline, my roommate lent me hers so that I could finish the assignment on time.", "截止日期前一晚我的电脑突然坏了，室友把她的借给我，我才得以按时完成作业。"),
    ("The city has opened several new bike lanes this year, hoping to encourage more people to cycle to work instead of driving their cars.", "今年市里新开通了几条自行车道，希望鼓励更多人骑车上班而不是开车。"),
    ("Although the museum ticket was a little expensive, the special exhibition about ancient Egypt was definitely worth the money and the long wait in line.", "虽然博物馆门票有点贵，但那场关于古埃及的特展绝对值回票价和漫长的排队等待。"),
    ("I signed up for the morning yoga class because the evening sessions are always full, and I actually enjoy starting my day with some exercise now.", "我报了早上的瑜伽课，因为晚上的课总是满员，而现在我真的很享受用运动开启一天。"),
    ("The landlord agreed to repaint the walls and fix the heating before we move in, which made the apartment much more attractive to us.", "房东同意在我们入住前重新粉刷墙壁并修好暖气，这让这套公寓对我们更有吸引力了。"),
    ("During the job interview, she was asked to describe a difficult problem she had solved, and her honest answer left a strong impression on the panel.", "面试时她被要求描述一个她解决过的难题，她诚恳的回答给面试官留下了深刻印象。"),
    ("My parents have finally learned how to make video calls, so now we talk face to face every Sunday even though we live in different cities.", "我父母终于学会了视频通话，现在虽然我们住在不同城市，但每个周日都能面对面聊天。"),
    ("The conference was moved online at the last minute, and to everyone's surprise, more people attended than in any previous year.", "会议在最后一刻改为线上举行，令所有人惊讶的是，参加人数比以往任何一年都多。"),
    ("He missed the last train home after the concert, so he shared a taxi with two strangers who happened to live in the same neighborhood.", "演唱会结束后他错过了末班车，于是和两个碰巧住在同一街区的陌生人拼了出租车。"),
    ("The store refused to give me a refund at first, but after I showed them the receipt and the photos, they apologized and returned my money.", "商店起初拒绝退款，但在我出示收据和照片后，他们道了歉并退了钱。"),
    ("We planned to climb the mountain on Saturday, but the heavy rain forced us to change our plans and visit the hot springs instead.", "我们原计划周六爬山，但大雨迫使我们改变计划，改去泡了温泉。"),
    ("She joined the company as an intern three years ago, and through hard work she has become one of the youngest team leaders in the department.", "三年前她以实习生身份加入公司，凭借努力工作已成为部门里最年轻的组长之一。"),
    ("The neighborhood committee organized a second-hand market last weekend, where residents sold old books, clothes, and furniture at very low prices.", "社区委员会上周末组织了一场二手市集，居民们以很低的价格出售旧书、衣服和家具。"),
    ("I have been learning to cook from online videos this year, and although I burned a few dishes at first, my friends now actually enjoy my dinners.", "今年我一直跟着网上的视频学做饭，虽然一开始烧糊了几道菜，但现在朋友们真的很喜欢吃我做的晚餐。"),
    ("The express delivery was supposed to arrive on Monday, but because of the holiday rush, I didn't receive my package until Thursday evening.", "快递本该周一到，但由于节日高峰，我直到周四晚上才收到包裹。"),
    ("If you register for the marathon before the end of this month, you will receive a free running shirt and a discount on next year's entry fee.", "如果你在本月底前报名马拉松，将获得一件免费跑步衫和明年报名费的折扣。"),
    ("The professor reminded us that the essay should be based on our own research and that copying from the internet would lead to serious consequences.", "教授提醒我们，论文必须基于自己的研究，从网上抄袭会导致严重后果。"),
    ("My sister's flight lands at six in the morning, so I set two alarms to make sure I wake up in time to pick her up.", "我姐姐的航班早上六点降落，所以我定了两个闹钟，确保能及时醒来去接她。"),
    ("The cafe on the corner changed its menu last month, and their new lemon cake has quickly become the most popular dessert in the area.", "街角的咖啡馆上个月换了菜单，他们新出的柠檬蛋糕很快成了这一带最受欢迎的甜点。"),
    ("After working overtime for two weeks, he finally took a day off and spent the whole afternoon sleeping and watching old movies at home.", "连续加班两周后，他终于休了一天假，整个下午都在家睡觉、看老电影。"),
    ("The students organized a small concert to raise money for the local children's hospital, and the tickets sold out within two days.", "学生们组织了一场小型音乐会为当地儿童医院筹款，门票两天内就卖光了。"),
    ("I always keep a small bag packed with basic things like a toothbrush and a charger, so I am ready for sudden business trips.", "我总是备着一个装有牙刷、充电器等基本用品的小包，以便随时应对突然的出差。"),
]
